import {timeSignature,tempoMark} from './meter.js';
import React,{useMemo,useRef,useState} from 'react';
import RhythmScore from './RhythmScore.jsx';
import PrintWorkspace from '../printing/PrintWorkspace.jsx';
import printBrand from '../etudes/assets/fretiva-lab-logo-print.png';
import printQr from '../etudes/score-source-qr.png';
import '../printing/a4Print.css';
import '../printing/printPreview.css';
import {paginatePrintPacks} from './printLayout.js';
import {useLanguage} from '../i18n/react.jsx';
export default function PrintPreview({pattern,stemDirection,mobile=false}) {
 const language=useLanguage();const t=(ko,en)=>language==='ko'?ko:en;
 const root=useRef();
 const [patterns,setPatterns]=useState(()=>(Array.isArray(pattern)?pattern:[pattern]).map((p,index)=>({...p,printKey:index,printSpace:0,printColumns:2,printMeta:`${timeSignature(p)} · ${tempoMark(p)} BPM · ${p.measures.length} ${t('마디','bars')}`,showMeta:true})));
 const footerText='https://guitarflow.vercel.app/';const [pageNumbers,setPageNumbers]=useState(true);const [selected,setSelected]=useState(0);const drag=useRef(null);
 const update=(index,patch)=>setPatterns(old=>old.map((p,i)=>i===index?{...p,...patch}:p));
 const selectedPack=patterns[selected];
 const pages=useMemo(()=>paginatePrintPacks(patterns,2),[patterns]);
 const change=patch=>{const next={};if('title' in patch)next.title=patch.title;if('description' in patch)next.printMeta=patch.description;if('showDescription' in patch)next.showMeta=patch.showDescription;if('spacing' in patch)next.printSpace=patch.spacing;if('pageNumbers' in patch)setPageNumbers(patch.pageNumbers);update(selected,next);};
 return <PrintWorkspace mobile={mobile} root={root} title={selectedPack.title} description={selectedPack.printMeta} showDescription={selectedPack.showMeta} pageNumbers={pageNumbers} spacing={selectedPack.printSpace} onChange={change} pageCount={pages.length} contentKey={patterns}
  controls={busy=><label>{t('선택한 팩 · 한 줄 보기','Selected pack · Bars per row')} <select value={selectedPack.printColumns} disabled={busy} onChange={e=>update(selected,{printColumns:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} {t('마디','bars')}</option>)}</select></label>}
  selector={busy=><label>{t('편집할 팩','Pack to edit')} <select value={selected} disabled={busy} onChange={e=>setSelected(Number(e.target.value))}>{patterns.map((p,i)=><option key={i} value={i}>{i+1}. {p.title}</option>)}</select></label>}
 >{({zoom,positioning,busy})=><div className="rt-print-pages" onPointerMove={e=>{const d=drag.current;if(d)update(d.key,{printSpace:Math.round(Math.max(0,Math.min(240,d.space+(e.clientY-d.y)/d.scale)))});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}>{pages.map((sections,i)=><div className="rt-print-frame" data-print-frame="" key={i} style={{width:794*zoom,height:1123*zoom}}><article className="rt-print-page" data-print-page="">{sections.map(({pattern:pack,offset,measures,space,columns},j)=><section className="rt-print-section" key={`${pack.printKey}-${offset}`} style={{paddingTop:space}} data-selected={selected===pack.printKey} onClick={()=>!busy&&setSelected(pack.printKey)} onFocus={()=>!busy&&setSelected(pack.printKey)} onPointerDown={e=>{if(busy||(mobile&&!positioning))return;setSelected(pack.printKey);if(e.target.closest('[contenteditable]'))return;e.preventDefault();const page=e.currentTarget.closest('.rt-print-page');drag.current={key:pack.printKey,y:e.clientY,space:pack.printSpace,scale:page.getBoundingClientRect().width/794};e.currentTarget.setPointerCapture(e.pointerId);}}><header className={`rt-print-drag${j===0?' rt-print-page-heading':''}`} title={t("위아래로 끌어 위치 조절","Drag vertically to adjust spacing")}>{j===0&&<><img className="rt-print-brand" src={printBrand} alt="FRETIVA LAB" draggable={false}/><img className="rt-print-qr" src={printQr} alt={t("FRETIVA LAB 접속 QR 코드","FRETIVA LAB website QR code")} draggable={false}/></>}<h1 className="rt-print-title" contentEditable={!busy} suppressContentEditableWarning role="textbox" aria-label={t("출력 제목 직접 편집","Edit print title directly")} onBlur={e=>update(pack.printKey,{title:e.currentTarget.textContent.slice(0,60)})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.currentTarget.blur();}}}>{pack.title}</h1>{pack.showMeta&&<p className="rt-print-description" contentEditable={!busy} suppressContentEditableWarning role="textbox" aria-label={t("출력 설명 직접 편집","Edit print description directly")} onBlur={e=>update(pack.printKey,{printMeta:e.currentTarget.textContent})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.currentTarget.blur();}}}>{pack.printMeta}</p>}</header><div className="rt-print-music" data-columns={columns} style={{'--print-columns':columns}}><RhythmScore connected={columns>1} measures={measures} meter={pack.meter} measureOffset={offset} previousMeasure={pack.measures[offset-1]} measureRepeats={pack.measureRepeats} stemDirection={stemDirection}/></div></section>)}<footer><span className="rt-print-site-address">{footerText}</span>{pageNumbers&&<span className="rt-print-page-number">{i+1} / {pages.length}</span>}</footer></article></div>)}</div>}</PrintWorkspace>;
}
