import React from 'react';
import {writtenTicks,tupletGroups} from './rhythmMath.js';
import {beatPositions,scoreCursorX} from './notationLayout.js';
export default function RhythmScore({measures,meter,position,selected,onSelect,preview=false,label,stemDirection='auto',measureOffset=0,previousMeasure,timeAligned=false,cellTicks=3,measureRepeats=[]}) {
 const positions=(beat,bi,m)=>timeAligned?beat.map((_,i)=>30+(beat.slice(0,i).reduce((v,n)=>v+n.ticks,0)+cellTicks/2)/beat.reduce((v,n)=>v+n.ticks,0)*316):beatPositions(beat,bi,m);
 const down=stemDirection==='down';const y=down?32:46;const flip=down?'translate(0 78) scale(1 -1)':undefined;
 const compact=preview&&meter===1;const layoutMeter=compact?2:meter;const staffEnd=compact?171:351;
 return <div className={`rt-score ${preview?'rt-preview':''}`} aria-label={label}>{measures.map((measure,localMi)=>{const mi=localMi+measureOffset;return <svg key={mi} className="rt-measure" data-stem-direction={down?'down':'up'} preserveAspectRatio={timeAligned?"none":undefined} viewBox={`0 0 ${compact?180:360} 78`} role="group" aria-label={`${mi+1}`} data-measure={mi}>
 {!timeAligned&&<text x="5" y={y+3} fill="var(--rt-measure-number, #84909c)" fontSize="10">{mi+1}</text>}<path d={`M23 ${y}H${staffEnd}M23 ${y-14}V${y+13}M${staffEnd} ${y-14}V${y+13}`} stroke="var(--rt-staff, #bac2ca)" fill="none"/>
 {measureRepeats[mi]&&<g className="rt-repeat-sign" aria-label="이 마디 두 번 연주" fill="var(--rt-ink, #252d36)" stroke="var(--rt-ink, #252d36)"><path d={`M20 ${y-15}v30M354 ${y-15}v30`} strokeWidth="3"/><path d={`M24 ${y-15}v30M350 ${y-15}v30`} strokeWidth="1"/><circle cx="28" cy={y-5} r="1.8"/><circle cx="28" cy={y+5} r="1.8"/><circle cx="346" cy={y-5} r="1.8"/><circle cx="346" cy={y+5} r="1.8"/></g>}
 {measure.map((beat,bi)=>{const width=316/layoutMeter;const left=30+bi*width;const xs=positions(beat,bi,layoutMeter);const groups=tupletGroups(beat);return <g key={bi}>
 {selected?.[0]===mi&&selected?.[1]===bi&&<rect x={left-6} y="7" width={width} height="62" rx="6" fill="#d7785e" opacity=".18" stroke="var(--rt-note-active, #d7785e)" strokeWidth="1"/>}
 {beat.map((n,ni)=>{const x=xs[ni];const stem=(beat.length>4?3:4)*(down?-1:1);const written=writtenTicks(n);const active=position?.event?.measure===mi&&position.event.beat===bi&&position.event.index===ni;const color=active?'var(--rt-note-active, #d45e4f)':'var(--rt-ink, #252d36)';const prevIndex=beat.slice(0,ni).findLastIndex(x=>!x.rest&&writtenTicks(x)<12);const after=beat.slice(ni+1).findIndex(x=>!x.rest&&writtenTicks(x)<12);const nextIndex=after<0?-1:ni+1+after;const prev=prevIndex>=0;const next=nextIndex>=0;const nextDouble=next&&beat.slice(ni+1,nextIndex+1).every(x=>writtenTicks(x)===3);const prevDouble=prev&&beat.slice(prevIndex,ni).every(x=>writtenTicks(x)===3);return <g key={ni} data-active={active||undefined} data-rest={n.rest} data-duration={n.ticks} data-written={written}>
 {n.rest ? <g transform={down?'translate(0 -14)':undefined}>{(written===12||written===18)?<path d={`M${x-3} 23l7 8-6 8 7 5q-12-3-8 10`} stroke={color} strokeWidth="2.8" fill="none"/>:<g fill={color} stroke={color} strokeWidth="1.8"><circle cx={x-2} cy="32" r="2.5"/><path d={`M${x-2} 34q5 1 7-6l-7 25`} fill="none"/>{written===3&&<><circle cx={x-4} cy="40" r="2.5"/><path d={`M${x-4} 42q5 1 7-6`} fill="none"/></>}</g>}</g>:
 <><ellipse cx={x} cy={y} rx={beat.length>4?3.5:5} ry={beat.length>4?2.8:3.5} transform={`rotate(-18 ${x} ${y})`} fill={color}/><g className="rt-stem-beams" transform={flip}><path d={`M${x+stem} 45V18`} stroke="var(--rt-ink, #252d36)" strokeWidth="1.6"/>
 {written<12&&next&&<path d={`M${x+stem} 18H${xs[nextIndex]+stem}`} stroke="var(--rt-ink, #252d36)" strokeWidth="3"/>}
 {written<12&&!next&&!prev&&<path d={`M${x+stem} 18q${beat.length>4?7:13} 7 3 17`} stroke="var(--rt-ink, #252d36)" strokeWidth="2" fill="none"/>}
 {written===3&&(nextDouble?<path d={`M${x+stem} 24H${xs[nextIndex]+stem}`} stroke="var(--rt-ink, #252d36)" strokeWidth="3"/>:prevDouble?null:next||prev?<path d={`M${x+stem} 24h${next?8:-8}`} stroke="var(--rt-ink, #252d36)" strokeWidth="3"/>:<path d={`M${x+stem} 24q${beat.length>4?7:12} 7 3 16`} stroke="var(--rt-ink, #252d36)" strokeWidth="2" fill="none"/>)}
 </g></> }
 {(written===9||written===18)&&<circle className="rt-augmentation-dot" cx={x+10} cy={y-(n.rest?11:4)} r="1.8" fill={color}/>}
 {n.tie&&ni===beat.length-1&&!n.rest&&<path className="rt-tie" transform={flip} d={`M${x+3} 54 Q${(x+(bi+1<meter?beatPositions(measure[bi+1],bi+1,layoutMeter)[0]:staffEnd))/2} 69 ${bi+1<meter?beatPositions(measure[bi+1],bi+1,layoutMeter)[0]-3:staffEnd} 54`} fill="none" stroke="var(--rt-ink, #252d36)" strokeWidth="1.4"/>}
 </g>;})}
 {groups.map((group,index)=>{const start=xs[group.start]-3,end=xs[group.end]+7,center=(start+end)/2;return <g key={index} className="rt-tuplet" data-tuplet={group.count} data-ratio={`${group.count}:${group.normal}`}><path transform={flip} d={`M${start} 12v-5H${end}v5`} stroke="var(--rt-measure-number, #58616b)" fill="none"/><rect x={center-5} y={down?65:0} width="10" height="13" fill="var(--rt-paper, white)"/><text x={center} y={down?75:10} textAnchor="middle" fontSize="10" fill="var(--rt-ink, #252d36)">{group.count}</text></g>;})}
 {onSelect&&<rect role="button" aria-label={`${mi+1} / ${bi+1}`} tabIndex="0" x={left-6} y="5" width={width} height="67" fill="transparent" onClick={()=>onSelect(mi,bi)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(mi,bi);}}}/>}
 </g>;})}
 {(localMi>0?measures[localMi-1]:previousMeasure)?.at(-1).at(-1).tie&&<path className="rt-tie rt-tie-continuation" transform={flip} d={`M23 54 Q${(23+positions(measure[0],0,layoutMeter)[0])/2} 66 ${positions(measure[0],0,layoutMeter)[0]-3} 54`} fill="none" stroke="var(--rt-ink, #252d36)" strokeWidth="1.4"/>}
 {position&&position.measure===mi&&<line className="rt-cursor" x1={(timeAligned?30+(position.tick/cellTicks)*cellTicks/measure[0].reduce((v,n)=>v+n.ticks,0)*316:scoreCursorX(measure,meter,position))} x2={(timeAligned?30+(position.tick/cellTicks)*cellTicks/measure[0].reduce((v,n)=>v+n.ticks,0)*316:scoreCursorX(measure,meter,position))} y1="6" y2="76" stroke="var(--rt-note-active, #d77865)" strokeWidth="1.2" opacity=".42"/>}
 </svg>;})}</div>;
}
