import {TIME_SIGNATURES,meterInfo,timeSignature} from './meter.js';
import {useTabletLayout} from '../layouts/TabletLayout.jsx';
import React,{useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Menu,Star} from 'lucide-react';
import useScreenHistory from './useScreenHistory.js';
import {useLanguage} from '../i18n/react.jsx';
import {getSharedAudioContext,getAudioBusInput,AUDIO_BUS_IDS} from '../audio/audioBus.js';
import {changePatternMeter,editorPresets,editorPresetForBeat,matchesBeatPreset,EDITOR_PRESET_GROUPS,practicePatterns,randomizeRange,repairTies,replacePatternBeat,clone,createPattern,examplePattern,emptyMeasure,randomMeasure,positionAt,measureStartTick,readStore,STORAGE_KEY} from './model.js';
import {builtinPacks,currentBuiltinDraft,resizeFoundation,copyPack,blankPack,PACK_FAMILIES,PACK_STEPS,LEVELS,STAGES} from './packs.js';
import {validateBeat,canSustain,setNoteAction} from './rhythmMath.js';
import {validPattern} from './model.js';
import {prepareBeatSounds,countInNumber} from './beatSounds.js';
import {BEAT_SOUND_OPTIONS,normalizeBeatSound} from './beatSoundOptions.js';
import {RhythmTransport} from './transport.js';
import RhythmScore from './RhythmScore.jsx';
import PrintPreview from './PrintPreview.jsx';
import PrintPreviewDialog from '../printing/PrintPreviewDialog.jsx';
import ProgressStyleSelect from './ProgressStyleSelect.jsx';
import GuideRoom from './GuideRoom.jsx';
import {PracticeBackingPanel} from '../etudes/PracticeFloatingTools.jsx';
import './rhythmTrainer.css';
import './whiteTheme.css';
import DesktopPackLibrary from './DesktopPackLibrary.jsx';
import './desktopRhythmTrainer.css';
function Modal({title,onClose,children,sheet=false,headerAction}) {const language=useLanguage();const ref=useRef();const [sheetHeight,setSheetHeight]=useState(null);const drag=useRef(null);const resizeSheet=value=>setSheetHeight(Math.max(180,Math.min(window.innerHeight*.85,value)));useEffect(()=>{const previous=document.activeElement;const background=document.querySelector('.appRuntime');const wasInert=background?.inert;if(background&&!sheet)background.inert=true;ref.current?.focus({preventScroll:true});return()=>{if(background&&!sheet)background.inert=wasInert;previous?.focus({preventScroll:true});};},[]);return createPortal(<div className={`rt-overlay ${sheet?'rt-sheet-overlay':''}`} onClick={e=>{if(!sheet&&e.target===e.currentTarget)onClose();}}><section ref={ref} tabIndex={-1} role="dialog" aria-modal={sheet?undefined:true} aria-label={title} className={`rt-dialog ${sheet?'rt-sheet':''}`} style={sheet&&sheetHeight?{height:sheetHeight,maxHeight:"85dvh"}:undefined} onKeyDown={e=>{if(e.key==='Escape')onClose();if(!sheet&&e.key==='Tab'){const els=[...ref.current.querySelectorAll('button,input,textarea,select,summary,[contenteditable="true"],[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus();}}}}>{sheet&&<div className="rt-sheet-resize" role="separator" aria-label={language==='ko'?'편집창 높이 조절':'Resize editor height'} aria-orientation="horizontal" aria-valuemin={180} aria-valuemax={Math.round(window.innerHeight*.85)} aria-valuenow={Math.round(sheetHeight||Math.min(window.innerHeight*.58,Math.max(220,window.innerHeight-350)))} tabIndex={0} onPointerDown={e=>{e.preventDefault();drag.current={y:e.clientY,height:ref.current.getBoundingClientRect().height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)resizeSheet(drag.current.height+drag.current.y-e.clientY);}} onPointerUp={e=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();resizeSheet(ref.current.getBoundingClientRect().height+(e.key==='ArrowUp'?40:-40));}}}><span/></div>}<header><h2>{title}</h2>{headerAction}<button onClick={onClose} aria-label={language==='ko'?'닫기':'Close'}>×</button></header><div className="rt-dialog-body">{children}</div></section></div>,document.body);}
function MobileLayout({children,screen}) {return <section className="rt-workspace rt-mobile" data-screen={screen}>{children}</section>;}
function DesktopLayout({children,screen}) {return <section className="rt-desktop"><div className="rt-workspace" data-screen={screen}>{children}</div></section>;}
function TabletLayout({children,screen}) {return <section className="rt-workspace rt-mobile rt-tablet" data-screen={screen}>{children}</section>;}
export default function RhythmTrainer({mobile,onExit,onOpenMenu,beatTone='tick',countVoiceMode='off'}) {
 const tablet=useTabletLayout();
 const [tabletWide,setTabletWide]=useState(()=>matchMedia('(min-width: 700px)').matches);
 useEffect(()=>{const query=matchMedia('(min-width: 700px)');const update=()=>setTabletWide(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 const lang=useLanguage();const t=(ko,en)=>lang==='ko'?ko:en;
 const [displaySettings,setDisplaySettings]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('rifflab-rhythm-display')||'{}')||{};return saved.stemDefaultVersion===2?saved:{...saved,stemDirection:'up',stemDefaultVersion:2};}catch{return {stemDirection:'up',stemDefaultVersion:2};}});
 const stemDirection=['auto','up','down'].includes(displaySettings.stemDirection)?displaySettings.stemDirection:'up';
 const progressStyle=[1,2,3,4,5].includes(displaySettings.progressStyle)?displaySettings.progressStyle:1;
 const selectedBeatSound=normalizeBeatSound(displaySettings.beatSound);
 const resolvedBeatSound=selectedBeatSound;
 const [backingTarget,setBackingTarget]=useState(null);
 const [guide,setGuide]=useState(null);const [printPack,setPrintPack]=useState(null);
 const [settingsDisplay,setSettingsDisplay]=useState({});const loadingPlay=useRef(false);const playRequest=useRef(0);
 useEffect(()=>{try{localStorage.setItem('rifflab-rhythm-display',JSON.stringify(displaySettings));}catch{setMessage(t('표시 설정을 저장하지 못했습니다. 현재 화면에서는 계속 사용할 수 있습니다.','Display settings could not be saved. You can continue using this screen.'));}},[displaySettings]);
 const [widePhone,setWidePhone]=useState(()=>matchMedia('(orientation: landscape) and (max-height: 600px)').matches);
 useEffect(()=>{const query=matchMedia('(orientation: landscape) and (max-height: 600px)');const update=()=>setWidePhone(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 const viewKey=tablet?(tabletWide?'tabletBars':'tabletSplitBars'):mobile?(widePhone?'mobileLandscapeBars':'mobilePortraitBars'):'desktopBars';
 const barsPerRow=[1,2,3,4].includes(displaySettings[viewKey])?displaySettings[viewKey]:(tablet?(tabletWide?2:1):mobile?(widePhone?2:1):2);
 const landscape=!tablet&&mobile&&widePhone;
 const packs=useMemo(()=>builtinPacks(lang),[lang]);
 const [learningStep,setLearningStep]=useState('all');const [managePacks,setManagePacks]=useState(false);const [deleteIds,setDeleteIds]=useState([]);const [printSelecting,setPrintSelecting]=useState(false);const [printIds,setPrintIds]=useState([]);const selectingPacks=managePacks||printSelecting;const selectionIds=printSelecting?printIds:deleteIds;const [family,setFamily]=useState('all');const [level,setLevel]=useState('all');const [editTarget,setEditTarget]=useState('score');
 const [initial]=useState(()=>readStore(localStorage));const [patterns,setPatterns]=useState(initial.patterns);const [p,setP]=useState(()=>currentBuiltinDraft(initial.draft,packs)||packs[0]);const [screen,setScreen]=useScreenHistory((next,previous)=>{
  pause();setTick(0);engine.current?.seek(0);setModal(null);setGuide(null);setPrintPack(null);
  if(previous==='edit'&&editOrigin.current){setP(editOrigin.current.pattern);editOrigin.current=null;}
 });const [libraryTab,setLibraryTab]=useState('recommended');const [selected,setSelected]=useState([0,0]);const [modal,setModal]=useState(null);const [settings,setSettings]=useState(null);const [draftBeat,setDraftBeat]=useState([]);const [presetGroup,setPresetGroup]=useState('basic');const [tieNext,setTieNext]=useState(false);const [difficulty,setDifficulty]=useState('medium');const [range,setRange]=useState([1,5]);const [audible,setAudible]=useState(false);const [running,setRunning]=useState(false);const [tick,setTick]=useState(0);const [message,setMessage]=useState('');const engine=useRef(null);const score=useRef(null);const editOrigin=useRef(null);
 // Activity reconnects layout effects when returning from another app menu.
 useLayoutEffect(()=>{
  setPrintSelecting(false);
  setPrintIds([]);
 },[]);
 const [backingClearance,setBackingClearance]=useState(90);
 useLayoutEffect(()=>{
  const footer=document.querySelector('.rt-workspace footer');if(!footer){if(!mobile)setBackingClearance(8);return;}
  const measure=()=>setBackingClearance(Math.max(0,window.innerHeight-footer.getBoundingClientRect().top)+8);
  measure();const observer=new ResizeObserver(measure);observer.observe(footer);window.addEventListener('resize',measure);
  return()=>{observer.disconnect();window.removeEventListener('resize',measure);};
 },[screen,mobile,landscape]);
 const title=p.title||t('새 연습팩','New practice pack');
 const core=p.core||p.measures[0];
 const meter=meterInfo(p);
 const [favoriteIds,setFavoriteIds]=useState(()=>{try{const ids=JSON.parse(localStorage.getItem('rifflab-rhythm-favorites')||'[]');return Array.isArray(ids)?ids.filter(id=>typeof id==='string'):[];}catch{return [];}});
 const favoritesOnly=libraryTab==='favorites';const [packSearch,setPackSearch]=useState('');
 useEffect(()=>{try{localStorage.setItem('rifflab-rhythm-favorites',JSON.stringify(favoriteIds));}catch{}},[favoriteIds]);
 const libraryItems=favoritesOnly?[...packs,...patterns].filter(item=>favoriteIds.includes(item.id)):libraryTab==='mine'?patterns:packs;
 const available=libraryItems.filter(item=>favoritesOnly||(libraryTab==='mine'?item.title.toLocaleLowerCase().includes(packSearch.trim().toLocaleLowerCase()):(learningStep==='all'||item.learningStep===learningStep)&&(family==='all'||item.family===family)&&(level==='all'||item.difficulty===level)));
 function selectCollection(id){setLibraryTab(id);setPrintSelecting(false);setPrintIds([]);setManagePacks(false);setDeleteIds([]);setLearningStep('all');setFamily('all');setLevel('all');}

 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({patterns,draft:p}));}catch{setMessage(t('저장 공간을 사용할 수 없습니다.','Local storage is unavailable.'));}},[patterns,p]);
 useEffect(()=>{engine.current?.configure(p);},[p]);
 useEffect(()=>{setRunning(false);return()=>{playRequest.current++;engine.current?.dispose();engine.current=null;};},[]);
 useEffect(()=>{const hide=()=>{if(document.hidden){playRequest.current++;engine.current?.pause();setRunning(false);}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),2400);return()=>clearTimeout(timer);},[message]);
 const countNumber=countInNumber(tick,p.meter,meter.beatTicks);
 const position=tick>=0?positionAt(p,tick):null;
 useEffect(()=>{if(!running||modal||!score.current)return;const row=score.current.querySelector(`[data-measure="${position?.measure}"]`);if(!row)return;const viewport=score.current.getBoundingClientRect();const bounds=row.getBoundingClientRect();if(bounds.top<viewport.top||bounds.bottom>viewport.bottom)score.current.scrollTop+=bounds.top-viewport.top;},[position?.measure,running,landscape,barsPerRow,screen,modal]);
 useLayoutEffect(()=>{
   if(!mobile||modal!=='beat'||editTarget!=='score'||!score.current)return;
   const row=score.current.querySelector(`[data-measure="${selected[0]}"]`),sheet=document.querySelector('.rt-sheet');
   if(!row||!sheet)return;const bounds=row.getBoundingClientRect(),viewport=score.current.getBoundingClientRect(),bottom=sheet.getBoundingClientRect().top-8;
   if(bounds.bottom>bottom)score.current.scrollTo({top:score.current.scrollTop+bounds.bottom-bottom,behavior:'smooth'});
   else if(bounds.top<viewport.top)score.current.scrollTo({top:score.current.scrollTop+bounds.top-viewport.top,behavior:'smooth'});
 },[modal,editTarget,selected]);
 function pause(){playRequest.current++;engine.current?.pause();setRunning(false);}
 function go(next){pause();setScreen(next);setTick(0);engine.current?.seek(0);}
 function openLibraryPack(item){setP(clone(item));setSelected([0,0]);go('setup');}
 function selectLibraryPack(item,event){
  // A double click must not toggle a print/delete selection twice.
  if(!mobile&&selectingPacks&&event.detail>1)return;
  if(selectingPacks){const update=printSelecting?setPrintIds:setDeleteIds;update(old=>old.includes(item.id)?old.filter(id=>id!==item.id):[...old,item.id]);return;}
  if(mobile&&libraryTab!=='mine'){openLibraryPack(item);return;}
  setP(clone(item));setSelected([0,0]);
 }
 function printSelectedPacks(){setPrintPack(clone(libraryItems.filter(item=>printIds.includes(item.id))));}
 async function play(startAt,fresh=false){if(loadingPlay.current)return;const fromMeasure=Number.isFinite(startAt);if(running&&!fromMeasure){pause();return;}if(fromMeasure){engine.current?.seek(startAt);setTick(startAt);if(running)return;}loadingPlay.current=true;const request=++playRequest.current;try{const ctx=getSharedAudioContext();await ctx.resume();if(request!==playRequest.current)return;if(ctx.state!=='running')throw Error();if(!engine.current){engine.current=new RhythmTransport(ctx,getAudioBusInput(AUDIO_BUS_IDS.SFX,ctx),(at,isRunning,heard=true)=>{setTick(at);setRunning(isRunning);setAudible(heard);});engine.current.configure(p);engine.current.tick=fromMeasure?startAt:tick;}const buffers=await prepareBeatSounds(ctx,resolvedBeatSound);if(request!==playRequest.current)return;engine.current.setBeatSound(resolvedBeatSound,buffers);if(fresh){engine.current.seek(0);}engine.current.start(!fromMeasure);setRunning(true);}catch{setMessage(t('소리를 시작하지 못했습니다. 재생을 다시 눌러 주세요.','Audio could not start. Press Play again.'));}finally{loadingPlay.current=false;}}
 function resizeBasic(delta){rewind();setP(old=>resizeFoundation(old,old.measures.length+delta));}
 function rewind(){pause();engine.current?.seek(0);setTick(0);score.current?.scrollTo({top:0});}
 function startMeasure(mi){setScreen('play');play(measureStartTick(p,mi));}
 function save(){const saved={...clone(p),source:'user',id:p.source==='builtin'||['example','triplets'].includes(p.id)||p.id.startsWith('practice-')?crypto.randomUUID():p.id,title};if(!validPattern(saved)){setMessage(t('음가 또는 이음줄을 확인해 주세요.','Check durations and ties.'));return false;}setP(saved);setPatterns(old=>[saved,...old.filter(x=>x.id!==saved.id)]);setMessage(t('내가 만든 팩에 저장했습니다.','Saved to My packs.'));return true;}
 function beginEdit(pattern=p){editOrigin.current={pattern:clone(p),screen:screen==='library'?'library':'setup'};const next=pattern.source==='builtin'?copyPack(pattern):clone(pattern);next.core=next.core||clone(next.measures[0]);delete next.stages;editOrigin.current.baseline=clone(next);editOrigin.current.isNew=pattern!==p;setP(next);setEditTarget('score');setSelected([0,0]);go('edit');}
 function cancelEdit(){const origin=editOrigin.current;if(origin)setP(origin.pattern);go(origin?.screen||'setup');editOrigin.current=null;}
 function finishEdit(){const origin=editOrigin.current;const musical=value=>JSON.stringify([value.title,value.meter,value.meterDenominator||4,value.core,value.measures,value.measureRepeats||[]]);if(origin&&!origin.isNew&&musical(p)===musical(origin.baseline)){setP({...origin.pattern,bpm:p.bpm,tone:p.tone,click:p.click,countIn:p.countIn,loop:p.loop});editOrigin.current=null;go('setup');return;}if(save()){editOrigin.current=null;go('setup');}}
 function openSettings(){setSettingsDisplay({...displaySettings,stemDirection,progressStyle,beatSound:selectedBeatSound});setSettings(clone(p));setModal('settings');}
 async function applySettings(){
   try {
     const nextSound=normalizeBeatSound(settingsDisplay.beatSound);
     if(engine.current&&nextSound!==resolvedBeatSound){const buffers=await prepareBeatSounds(engine.current.ctx,nextSound);engine.current.setBeatSound(nextSound,buffers);}
     setDisplaySettings({...settingsDisplay,beatSound:nextSound});
     if(['bpm','tone','click','countIn'].some(key=>p[key]!==settings[key]))setP({...p,bpm:settings.bpm,tone:settings.tone,click:settings.click,countIn:settings.countIn});
     setModal(null);
   }catch{setMessage(t('박자 소리를 불러오지 못했습니다. 다시 시도해 주세요.','Could not load the beat sound. Try again.'));}
 }
 function changeMeter(signature){pause();setP(changePatternMeter(p,signature));setSelected([0,0]);setTick(0);engine.current?.seek(0);setMessage(t('박 길이 조정 · 빈칸은 쉼표, 초과 음은 줄임','Beats resized: padded with rests; overflow shortened.'));}
 function choose(mi,bi,target='score'){const beat=target==='core'?core[bi]:p.measures[mi][bi];setEditTarget(target);setSelected([mi,bi]);setDraftBeat(clone(beat));setTieNext(Boolean(beat.at(-1).tie));const preset=editorPresetForBeat(beat,p);setPresetGroup(preset?.group||'basic');setModal('beat');}
 function closeBeat(){setModal(editTarget==='core'?'core':null);}
 function replaceBeat(beat){if(!validateBeat(beat,meter.beatTicks))return;const value=clone(beat);value.forEach(n=>delete n.tie);if(tieNext&&canSustain(followingBeat?.[0])&&canSustain(value.at(-1)))value.at(-1).tie=true;
   if(editTarget==='core'){const next=clone(core);next[selected[1]]=value;next.forEach((b,i)=>b.forEach((n,j)=>{if(n.tie&&(j!==b.length-1||!canSustain(n)||!canSustain(next[i+1]?.[0])))delete n.tie;}));setP({...p,core:next});}
   else setP(old=>replacePatternBeat(old,selected[0],selected[1],value));closeBeat();}
 const followingBeat=editTarget==='core'?core[selected[1]+1]:p.measures.flat()[selected[0]*p.meter+selected[1]+1];
 const scoreView=<div className={`rt-score-scroll ${landscape?'rt-landscape-score':''}`} ref={score} data-bars-per-row={barsPerRow} style={{'--rt-bars-per-row':barsPerRow}}><RhythmScore connected={barsPerRow>1} progressStyle={progressStyle} measureRepeats={p.measureRepeats} stemDirection={stemDirection} measures={p.measures} meter={p.meter} position={screen==='play'&&(!running||audible)?position:null} selected={screen==='edit'?selected:null} onSelect={screen==='edit'?(mi,bi)=>choose(mi,bi):null} onMeasureSelect={screen==='setup'||screen==='play'?startMeasure:null} measureActionLabel={mi=>t(`${mi+1}마디부터 재생`, `Play from bar ${mi+1}`)} label={t('리듬 악보','Rhythm score')}/></div>;
 const backButton=<button onClick={()=>screen==='library'?onExit():screen==='edit'?cancelEdit():go(screen==='play'?'setup':'library')} aria-label={screen==='edit'?t('편집 취소','Cancel editing'):t('뒤로','Back')}>{screen==='edit'?t('취소','Cancel'):'‹'}</button>;
 const headerActions=<div className="rt-header-actions">{screen!=='library'&&<button onClick={()=>{pause();setGuide({pack:clone(p)});}}>{t('가이드실','Guide room')}</button>}{screen==='library'?(mobile?<button className="rt-menu-button" onClick={onOpenMenu} aria-label={t('메뉴','Menu')}><Menu size={17} aria-hidden="true"/>{t('메뉴','Menu')}</button>:null):screen==='edit'?null:<><button onClick={()=>{pause();setPrintPack(clone(p));}}>{mobile?t('PDF 미리보기','PDF preview'):t('인쇄 · PDF','Print · PDF')}</button><button onClick={()=>beginEdit()}>{p.source==='builtin'?t('복사·편집','Copy & edit'):t('편집','Edit')}</button></>}</div>;
 const rowView=landscape&&<div className="rt-landscape-view" role="group" aria-label={t('한 줄 보기','Bars per row')}><span>{t('한 줄 보기','Bars per row')}</span>{[1,2,3,4].map(n=><button key={n} aria-pressed={barsPerRow===n} aria-label={t(`한 줄에 ${n}마디 보기`,`${n} bars per row`)} onClick={()=>setDisplaySettings(old=>({...old,[viewKey]:n}))}>{n}</button>)}</div>;
 const compactDesktopHeader=!mobile&&(screen==='setup'||screen==='play');
 const header=<header className="rt-header">{backButton}<strong className={compactDesktopHeader?'rt-pack-heading':undefined}>{compactDesktopHeader?title:screen==='library'?t('리듬 보관함','Rhythm library'):screen==='edit'?t('패턴 편집','Edit pattern'):screen==='setup'?t('연습 준비','Practice setup'):t('리듬 연습','Rhythm practice')}</strong>{compactDesktopHeader&&<span className="rt-header-meter">{meter.signature}</span>}{headerActions}</header>;
 const libraryCollections=<nav className="rt-tabs">{[['mine',t('내가 만든 팩','My packs')],['recommended',t('기본 제공 팩','Built-in packs')]].map(([id,label])=><button key={id} className={libraryTab===id?'selected':''} onClick={()=>selectCollection(id)}>{label}</button>)}<button className={`rt-favorites-toggle ${favoritesOnly?'selected':''}`} aria-label={t('즐겨찾기만 보기','Favorites only')} aria-pressed={favoritesOnly} onClick={()=>selectCollection('favorites')}><Star size={15} strokeWidth={1.8} fill={favoritesOnly?'currentColor':'none'} aria-hidden="true"/>{t('즐겨찾기','Favorites')}</button></nav>;
 const libraryFilters=<>{libraryTab==='mine'&&<label className="rt-pack-search"><span aria-hidden="true">⌕</span><input type="search" value={packSearch} onChange={e=>setPackSearch(e.target.value)} aria-label={t('저장 팩 검색','Search saved packs')} placeholder={t('저장 팩 검색','Search saved packs')}/></label>}{libraryTab==='recommended'&&<div className="rt-library-filters"><label>{t('리듬 유형','Rhythm type')}<select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">{t('전체 유형','All types')}</option>{PACK_FAMILIES.map(([id,ko,en])=><option key={id} value={id}>{t(ko,en)}</option>)}</select></label><label>{t('유형 내 난이도','Level within type')}<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">{t('전체 난이도','All levels')}</option>{LEVELS.map(([id,ko,en])=><option key={id} value={id}>{t(ko,en)}</option>)}</select></label></div>}{libraryTab==='recommended'&&<nav className="rt-tools" aria-label={t('학습 단계','Learning stage')}>{[['all','전체 단계','All stages'],...PACK_STEPS].map(([id,ko,en])=><button key={id} aria-pressed={learningStep===id} onClick={()=>setLearningStep(id)}>{t(ko,en)}</button>)}</nav>}</>;
 const libraryToolbar=<div className="rt-library-summary"><small className="rt-result-count">{available.length} {t('개 연습팩','practice packs')}</small><div className="rt-library-actions"><span className="rt-backing-target" ref={setBackingTarget}/><button onClick={()=>{pause();setGuide({pack:null});}}>{t('가이드실','Guide room')}</button><button className="rt-library-print" aria-pressed={printSelecting} onClick={()=>{setPrintSelecting(!printSelecting);setPrintIds([]);setManagePacks(false);setDeleteIds([]);}}>{printSelecting?t('선택 취소','Cancel selection'):mobile?t('PDF 미리보기','PDF preview'):t('인쇄 · PDF','Print · PDF')}</button></div>{libraryTab==='mine'&&<button className="rt-manage-packs" aria-pressed={managePacks} onClick={()=>{setManagePacks(!managePacks);setDeleteIds([]);setPrintSelecting(false);setPrintIds([]);}}>{managePacks?t('편집 완료','Done editing'):t('편집','Edit')}</button>}{libraryTab==='mine'&&<button className="rt-create-inline" onClick={()=>{const next=blankPack();next.title=t('새 연습팩','New practice pack');beginEdit(next);}}>＋ {t('신규 생성','Create new')}</button>}</div>;
 const libraryCards=<div className="rt-library-list">{available.map(item=><div className="rt-pack-card-wrap" key={item.id}><button className={`rt-card ${(selectingPacks?selectionIds.includes(item.id):p.id===item.id)?'selected':''}`} key={item.id} data-pack={item.id} aria-pressed={selectingPacks?selectionIds.includes(item.id):p.id===item.id} onClick={event=>selectLibraryPack(item,event)} onDoubleClick={!mobile&&!selectingPacks?()=>openLibraryPack(item):undefined} onKeyDown={!mobile&&!selectingPacks?event=>{if(event.key==='Enter'){event.preventDefault();openLibraryPack(item);}}:undefined}><strong>{selectingPacks?(selectionIds.includes(item.id)?'☑ ':'☐ '):''}{item.title}</strong><RhythmScore stemDirection={stemDirection} measures={[item.core||item.measures[0]]} meter={(item.core||item.measures[0]).length} preview label={t('핵심 패턴 악보','Core pattern score')}/></button><button className="rt-pack-favorite" aria-pressed={favoriteIds.includes(item.id)} aria-label={`${item.title} · ${favoriteIds.includes(item.id)?t('즐겨찾기 해제','Remove favorite'):t('즐겨찾기 추가','Add favorite')}`} onClick={()=>setFavoriteIds(old=>old.includes(item.id)?old.filter(id=>id!==item.id):[...old,item.id])}><Star size={20} strokeWidth={1.7} fill={favoriteIds.includes(item.id)?'currentColor':'none'} aria-hidden="true"/></button></div>)}{!available.length&&<p>{favoritesOnly?t('즐겨찾기한 팩이 없습니다. 별표를 눌러 추가해 주세요.','No favorites. Use a star to add packs.'):t('이 조건의 팩이 없습니다. 빈 악보에서 새 팩을 만들 수 있어요.','No matching packs. Create one from a blank score.')}</p>}</div>;
 const librarySelection=<footer>{printSelecting?<button className="rt-primary" disabled={!printIds.length} onClick={printSelectedPacks}>{mobile?t('선택한 팩 미리보기','Preview selected packs'):t('선택한 팩 인쇄 · PDF','Print selected packs')} ({printIds.length})</button>:managePacks?<button className="rt-primary" disabled={!deleteIds.length} onClick={()=>setModal('delete-packs')}>{t('선택한 팩 삭제','Delete selected packs')} ({deleteIds.length})</button>:libraryTab==='mine'?<div className="rt-saved-pack-load"><small>{available.some(item=>item.id===p.id)?title:t('팩을 선택해 주세요','Select a pack')}</small><button className="rt-primary" disabled={!available.some(item=>item.id===p.id)} onClick={()=>go('setup')}>{t('불러오기','Load')}</button></div>:<button className="rt-primary" disabled={!available.some(item=>item.id===p.id)} onClick={()=>go('setup')}>{t('선택한 팩 열기','Open selected pack')} →</button>}</footer>;
 const selectedLibraryPack=available.find(item=>item.id===p.id);
 const desktopSelection=<>
  <div className="rt-library-selection-copy"><strong>{selectingPacks?t(selectionIds.length+'개 팩 선택',selectionIds.length+' packs selected'):selectedLibraryPack?.title||t('연습팩을 선택해 주세요','Select a practice pack')}</strong><small>{selectingPacks?t('목록에서 함께 사용할 팩을 선택하세요.','Select packs from the list.'):t('한 번 클릭해 선택 · 더블클릭 또는 Enter로 열기','Click to select · Double-click or press Enter to open')}</small></div>
  {printSelecting?<button className="rt-primary" disabled={!printIds.length} onClick={printSelectedPacks}>{t('선택한 팩 인쇄 · PDF','Print selected packs')} ({printIds.length})</button>:managePacks?<button className="rt-primary" disabled={!deleteIds.length} onClick={()=>setModal('delete-packs')}>{t('선택한 팩 삭제','Delete selected packs')} ({deleteIds.length})</button>:<button className="rt-primary" disabled={!selectedLibraryPack} onClick={()=>go('setup')}>{t('연습팩 열기','Open practice pack')} →</button>}
 </>;
 const content=<>{(!landscape||screen==='library')&&(mobile||screen!=='library')&&header}{screen==='library'?(mobile?<>{libraryCollections}{libraryFilters}{libraryToolbar}{libraryCards}{librarySelection}</>:<DesktopPackLibrary title={t('리듬 보관함','Rhythm library')} collections={libraryCollections} filters={libraryFilters} toolbar={libraryToolbar} selection={desktopSelection}>{libraryCards}</DesktopPackLibrary>):<>
 {!compactDesktopHeader&&<div className={`rt-meta ${landscape?'rt-landscape-heading':''}`}>{landscape&&backButton}{screen==='edit'?<input aria-label={t('패턴 제목','Pattern title')} value={p.title} placeholder={title} onChange={e=>setP({...p,title:e.target.value})}/>:<strong>{title}</strong>}{screen==='edit'?<label className="rt-edit-meter">{t('박자표','Meter')} <select aria-label={t('편집 박자표','Edit time signature')} value={meter.signature} onChange={e=>changeMeter(e.target.value)}>{TIME_SIGNATURES.map(m=><option key={m} value={m}>{m}</option>)}</select></label>:<span>{screen==='play'?`${p.bpm} BPM · ${meter.signature}`:`${meter.signature} · ${p.measures.length} ${t('마디','bars')}`}</span>}{rowView}</div>}

 <div className={`rt-quick ${p.learningStep==='foundation'&&screen!=='edit'?'rt-quick-foundation':''} ${landscape?'rt-landscape-actions':''}`}><span title={p.stages?.[position?.measure]?t(...STAGES[p.stages[position.measure]]):undefined}>{tick<0?t('카운트인','Count-in')+` ${countNumber||t('준비','Ready')}`:screen==='play'?`${String((position?.measure||0)+1).padStart(2,'0')} / ${String(p.measures.length).padStart(2,'0')} ${t('마디','bars')}${position?.repeatPass?` · ${position.repeatPass}/2`:''}`:`${p.bpm} BPM`}</span><button onClick={()=>{pause();setModal('core');}}>{t('핵심 패턴','Core pattern')}</button>{screen!=='edit'&&p.learningStep==='foundation'&&<div className="rt-bar-count" aria-label={t('연습 마디 수','Practice bar count')}><button aria-label={t('마디 줄이기','Fewer bars')} disabled={p.measures.length<=1} onClick={()=>resizeBasic(-1)}>−</button><span>{p.measures.length} {t('마디','bars')}</span><button aria-label={t('마디 늘리기','More bars')} disabled={p.measures.length>=16} onClick={()=>resizeBasic(1)}>＋</button></div>}{landscape&&headerActions}<span className="rt-backing-target" ref={setBackingTarget}/>{screen!=='play'?<button onClick={openSettings}>{t('BPM·음색 설정','BPM · Sound')} ⚙</button>:<button aria-pressed={p.loop} onClick={()=>setP({...p,loop:!p.loop})}>{t('반복','Loop')} {p.loop?'ON':'OFF'}</button>}</div>
 {meter.compound&&<small className="rt-meter-context">{Array(meter.beats).fill(3).join('+')} · {t(`큰 박 ${meter.beats}개 · 점4분음표 = ${p.bpm} BPM`,`${meter.beats} main beats · dotted quarter = ${p.bpm} BPM`)}</small>}
 {screen==='edit'&&<label className="rt-repeat-option rt-repeat-toolbar">{selected[0]+1}{t('마디 · 한 번 더 반복',' bar · repeat once more')}<input type="checkbox" checked={!!p.measureRepeats?.[selected[0]]} onChange={e=>setP({...p,measureRepeats:p.measures.map((_,i)=>i===selected[0]?e.target.checked:!!p.measureRepeats?.[i])})}/></label>}{scoreView}{screen==='play'&&countNumber!==null&&<div className="rt-count-in" role="status" aria-label={t('카운트인','Count-in')}><span>{!running?t('카운트인 일시정지','Count-in paused'):countNumber===0?t('한 박 뒤 시작합니다','Starting in one beat'):t('카운트인','Count-in')}</span><strong className={!running||countNumber===0?'rt-count-ready':undefined}>{!running?'Ⅱ':countNumber||t('준비','Ready')}</strong><small>{Array.from({length:p.meter},(_,i)=>i+1).join(' → ')}</small><div className="rt-count-actions">{!running&&<button className="rt-primary" onClick={play}>{t('카운트인 다시 시작','Restart count-in')}</button>}<button onClick={()=>go('setup')}>{t('취소','Cancel')}</button></div></div>}
 {screen==='edit'?<><div className="rt-tools"><button disabled={p.measures.length>=128} onClick={()=>setP({...p,measures:[...p.measures,emptyMeasure(p)],...(p.measureRepeats?{measureRepeats:[...p.measureRepeats,false]}:{})})}>＋ {t('마디','Bar')}</button><button onClick={()=>choose(Math.min(selected[0],p.measures.length-1),Math.min(selected[1],p.meter-1))}>{t('음표·쉼표','Notes · Rests')}</button><button onClick={()=>{setRange([selected[0]+1,selected[0]+1]);setModal('random');}}>{t('랜덤','Random')}</button></div><footer><button className="rt-primary" onClick={finishEdit}>{t('변경 내용 저장','Save changes')} →</button></footer></>:screen==='setup'?<footer className={`rt-start-controls ${mobile?'rt-start-mobile':'rt-start-desktop'}`}><div className="rt-start-settings"><div className="rt-start-tempo" role="group" aria-label={t('시작 BPM','Starting BPM')}><button aria-label="BPM −10" disabled={p.bpm<=30} onClick={()=>setP({...p,bpm:Math.max(30,p.bpm-10)})}>−10</button><button aria-label={t('BPM 낮추기','Decrease BPM')} disabled={p.bpm<=30} onClick={()=>setP({...p,bpm:p.bpm-1})}>−</button><label><input aria-label={t('연습 BPM','Practice BPM')} type="number" min="30" max="240" value={p.bpm} onChange={e=>{const bpm=Number(e.target.value);if(Number.isFinite(bpm))setP({...p,bpm:Math.max(30,Math.min(240,bpm))});}}/><span>BPM</span></label><button aria-label={t('BPM 높이기','Increase BPM')} disabled={p.bpm>=240} onClick={()=>setP({...p,bpm:p.bpm+1})}>＋</button><button aria-label="BPM +10" disabled={p.bpm>=240} onClick={()=>setP({...p,bpm:Math.min(240,p.bpm+10)})}>＋10</button></div><button onClick={openSettings} aria-label={t('시작 설정','Start settings')}>⚙ {t('시작 설정','Start settings')} · {t('카운트인','Count-in')} {p.countIn?'ON':'OFF'}</button></div><button className="rt-primary" onClick={()=>{go('play');play(undefined,true);}}>{p.bpm} BPM · {t('연습 시작','Start practice')} ▶</button></footer>:<footer className="rt-transport"><button onClick={openSettings}>{t('음색','Sound')} ⚙</button><button aria-label="BPM −10" disabled={p.bpm<=30} onClick={()=>setP({...p,bpm:Math.max(30,p.bpm-10)})}>−10</button><button aria-label="BPM −" disabled={p.bpm<=30} onClick={()=>setP({...p,bpm:p.bpm-1})}>−</button><b>{p.bpm}<small> BPM</small></b><button aria-label="BPM +" disabled={p.bpm>=240} onClick={()=>setP({...p,bpm:p.bpm+1})}>＋</button><button aria-label="BPM +10" disabled={p.bpm>=240} onClick={()=>setP({...p,bpm:Math.min(240,p.bpm+10)})}>＋10</button><button title={t('처음으로','Back to start')} aria-label={t('처음으로','Back to start')} onClick={rewind}>|‹</button><button aria-label={t('다음 마디','Next bar')} onClick={()=>{const at=measureStartTick(p,((position?.measure||0)+1)%p.measures.length);engine.current?.seek(at);setTick(at);}}>›|</button><button className="rt-primary" aria-label={running?t('일시정지','Pause'):t('재생','Play')} onClick={play}>{running?'Ⅱ':'▶'}</button></footer>}
 </>}{message&&<button className="rt-message" role="status" onClick={()=>setMessage('')}>{message} ×</button>}</>;
 return <>{guide&&<GuideRoom progressStyle={progressStyle} onProgressStyle={progressStyle=>setDisplaySettings(old=>({...old,progressStyle}))} initialTone={p.tone} initialBpm={p.bpm} initialPack={guide.pack} mobile={mobile} stemDirection={stemDirection} beatSound={resolvedBeatSound} onBeatSound={beatSound=>setDisplaySettings(old=>({...old,beatSound}))} onClose={()=>setGuide(null)}/>} {tablet?<TabletLayout screen={screen}>{content}</TabletLayout>:mobile?<MobileLayout screen={screen}>{content}</MobileLayout>:<DesktopLayout screen={screen}>{content}</DesktopLayout>}
 <PracticeBackingPanel mobile={mobile} scope="rhythm-trainer" triggerTarget={backingTarget} clearance={backingClearance}/>
 {printPack&&<PrintPreviewDialog mobile={mobile} onClose={()=>setPrintPack(null)}><PrintPreview pattern={printPack} stemDirection={stemDirection} mobile={mobile}/></PrintPreviewDialog>}
 {modal==='delete-packs'&&<Modal title={t('선택한 팩 삭제','Delete selected packs')} onClose={()=>setModal(null)}><p>{t(`${deleteIds.length}개 팩을 삭제할까요? 삭제 후 되돌릴 수 없습니다.`,`Delete ${deleteIds.length} packs? This cannot be undone.`)}</p><ul>{patterns.filter(item=>deleteIds.includes(item.id)).map(item=><li key={item.id}>{item.title}</li>)}</ul><button onClick={()=>setModal(null)}>{t('취소','Cancel')}</button><button className="rt-primary" onClick={()=>{const remaining=patterns.filter(item=>!deleteIds.includes(item.id));setPatterns(remaining);if(deleteIds.includes(p.id))setP(clone(remaining[0]||packs[0]));setDeleteIds([]);setModal(null);setMessage(t('선택한 팩을 삭제했습니다.','Selected packs deleted.'));}}>{t('삭제','Delete')}</button></Modal>}
 {modal==='core'&&<Modal title={t('핵심 패턴','Core pattern')} onClose={()=>setModal(null)}><p>{title} · {core.length} {t('박','beats')}</p><RhythmScore stemDirection={stemDirection} measures={[core]} meter={core.length} preview onSelect={screen==='edit'?(mi,bi)=>choose(mi,bi,'core'):null}/>{screen==='edit'?<><label>{t('핵심 패턴 길이','Core length')}<select value={core.length} onChange={e=>{const length=Number(e.target.value);const next=Array.from({length},(_,i)=>clone(core[i]||emptyMeasure(p)[0]));next.at(-1).forEach(n=>delete n.tie);setP({...p,core:next});}}>{[...new Set([1,2,p.meter])].map(n=><option key={n} value={n}>{n} {t('박','beats')}</option>)}</select></label><p>{t('악보의 박을 눌러 음표·쉼표를 입력하세요. 연습 마디는 별도로 편집합니다.','Select a beat to enter notes or rests. Edit practice bars separately.')}</p></>:<p>{t('이 패턴을 익힌 뒤 위치와 주변 리듬을 바꾸어 연습합니다.','Learn this pattern, then vary its position and surrounding rhythm.')}</p>}<button className="rt-primary" onClick={()=>setModal(null)}>{t('악보로 돌아가기','Return to score')}</button></Modal>}
 {modal==='settings'&&<Modal title={t('연습 설정','Practice settings')} onClose={()=>setModal(null)}><label>{t('한 줄에 보일 마디 수','Bars per row')}<select aria-label={t('마디 보기','Bar layout')} value={settingsDisplay[viewKey]||barsPerRow} onChange={e=>setSettingsDisplay({...settingsDisplay,[viewKey]:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}{t('마디',' bars')}</option>)}</select></label><ProgressStyleSelect value={settingsDisplay.progressStyle} onChange={progressStyle=>setSettingsDisplay({...settingsDisplay,progressStyle})}/><label>{t('음표 기둥·빔 방향','Stem and beam direction')}<select aria-label={t('음표 기둥·빔 방향','Stem and beam direction')} value={settingsDisplay.stemDirection} onChange={e=>setSettingsDisplay({...settingsDisplay,stemDirection:e.target.value})}>{[['auto',t('자동','Auto')],['up',t('위','Up')],['down',t('아래','Down')]].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>{t('박자 소리 · 카운트인','Beat sound · Count-in')}<select aria-label={t('박자 소리 · 카운트인','Beat sound · Count-in')} value={settingsDisplay.beatSound} onChange={e=>setSettingsDisplay({...settingsDisplay,beatSound:e.target.value})}>{BEAT_SOUND_OPTIONS.map(o=><option key={o.id} value={o.id}>{t(o.ko,o.en)}</option>)}</select></label><label>{meter.compound?t('점4분음표 BPM','Dotted-quarter BPM'):'BPM'}<input type="number" min="30" max="240" value={settings.bpm} onChange={e=>setSettings({...settings,bpm:Number(e.target.value)})}/></label><p>{t('음표가 시작할 때 들리는 소리','Sound at each note onset')}</p><div className="rt-options">{[['wood',t('우드블록','Woodblock')],['rim',t('림샷','Rimshot')],['clap',t('클랩','Clap')]].map(([tone,name])=><button key={tone} aria-pressed={settings.tone===tone} onClick={()=>setSettings({...settings,tone})}>{name}</button>)}</div>{[['click',t('기준 박 클릭','Beat click')],['countIn',t('시작 전 카운트인 · 1마디','Count-in · 1 bar')]].map(([key,label])=><label key={key}>{label}<input type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}<small>{t('쉼표 구간에는 패턴 소리가 나지 않아요.','Rests do not trigger the pattern sound.')}</small><button className="rt-primary" disabled={!Number.isFinite(settings.bpm)||settings.bpm<30||settings.bpm>240} onClick={applySettings}>{t('적용하기','Apply')}</button></Modal>}
 {modal==='beat'&&<Modal sheet headerAction={<button className="rt-primary" disabled={!validateBeat(draftBeat,meter.beatTicks)} onClick={()=>replaceBeat(draftBeat)}>{t('적용','Apply')}</button>} title={
   (editTarget==='core'?t('핵심','Core'):String(selected[0]+1)+' '+t('마디','bar'))+' · '+(selected[1]+1)+' '+t('박 편집','beat')
 } onClose={closeBeat}>
  {editTarget==='score'&&<label className="rt-repeat-option">{t('이 마디 한 번 더 반복 (도돌이표)','Repeat this bar once more')}<input type="checkbox" checked={!!p.measureRepeats?.[selected[0]]} onChange={e=>setP({...p,measureRepeats:p.measures.map((_,i)=>i===selected[0]?e.target.checked:!!p.measureRepeats?.[i])})}/></label>}
  <label className="rt-tie-option">{t('다음 박 첫 음까지 이음줄','Tie to the first note of the next beat')}<input type="checkbox" checked={tieNext} disabled={!canSustain(followingBeat?.[0])||!canSustain(draftBeat.at(-1))} onChange={e=>setTieNext(e.target.checked)}/></label>
  <div className="rt-preset-groups" role="tablist" aria-label={t('한 박 리듬 분류','Beat preset groups')}>
   {EDITOR_PRESET_GROUPS.map(([id,ko,en])=><button key={id} id={'rt-preset-tab-'+id} role="tab" aria-controls="rt-preset-panel" aria-selected={presetGroup===id} onClick={()=>setPresetGroup(id)}>{t(ko,en)}</button>)}
  </div>
  <div id="rt-preset-panel" className="rt-beat-presets" role="tabpanel" aria-labelledby={'rt-preset-tab-'+presetGroup}>
   {editorPresets(presetGroup,p).map(item=><button key={item.id} aria-label={t(item.ko,item.en)} aria-pressed={matchesBeatPreset(draftBeat,item.beat)} onClick={()=>{setDraftBeat(clone(item.beat));if(item.beat.at(-1).rest)setTieNext(false);}}><RhythmScore stemDirection={stemDirection} measures={[[item.beat]]} meter={1} preview/><span>{t(item.ko,item.en)}</span></button>)}
  </div>
 <div className="rt-note-actions"><p>{t('음별 동작','Note actions')}</p><div>{draftBeat.map((n,i)=><label key={i}>{i+1}<select aria-label={t(`${i+1}번째 음 동작`, `Note ${i+1} action`)} value={n.rest?'rest':n.muted?'mute':'hit'} onChange={e=>{const action=e.target.value;setDraftBeat(old=>old.map((note,j)=>i===j?setNoteAction(note,action):note));if(i===draftBeat.length-1&&action!=='hit')setTieNext(false);}}><option value="hit">{t('치기','Play')}</option><option value="mute">{t('뮤트','Mute')}</option><option value="rest">{t('쉼','Rest')}</option></select></label>)}</div><RhythmScore stemDirection={stemDirection} measures={[[draftBeat]]} meter={1} preview/><small>{t('뮤트는 줄을 눌러 소리를 막고 짧게 칩니다. 쉼은 치지 않습니다.','A muted hit strikes damped strings briefly. A rest has no strike.')}</small></div>
 </Modal>}
 {modal==='random'&&<Modal title={t('랜덤 조합','Randomize')} onClose={()=>setModal(null)}><label>{t('박자표','Time signature')}<select value={meter.signature} onChange={e=>changeMeter(e.target.value)}>{TIME_SIGNATURES.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>{t('난이도','Difficulty')}<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{[['easy',t('초급 · 기본 리듬 조합','Easy · basic combinations')],['medium',t('중급 · 음가와 쉼표 변화','Medium · varied notes and rests')],['hard',t('고급 · 엇박·이음줄·셋잇단','Advanced · syncopation, ties, triplets')]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{[0,1].map(i=><label key={i}>{i===0?t('시작 마디','First bar'):t('끝 마디','Last bar')}<input type="number" min="1" max={p.measures.length} value={range[i]} onChange={e=>setRange(range.map((x,j)=>j===i?Number(e.target.value):x))}/></label>)}<button className="rt-primary" disabled={!range.every(Number.isInteger)||range[0]<1||range[1]>p.measures.length||range[1]<range[0]} onClick={()=>{setP(randomizeRange(p,range[0]-1,range[1]-1,difficulty));setModal(null);}}>{t('선택 구간 생성','Generate selected bars')}</button></Modal>}
 </>;
}
