import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {listPdfs,getPdf,findPdf,savePdf,patchPdf,deletePdf,fingerprintPdf,storageError,downloadBlob,exportPdfLibrary,readBackup} from './pdfLibrary.js';
import {inspectPdf} from './pdfRenderer.js';
import {loadLibrary,saveLibraryDocument} from '../etudes/scoreLibrary.js';
import {createBlankDocument,copyDocument,hasEditableShape} from '../etudes/scoreModel.js';
import {upgradeDocument} from '../etudes/scoreDocument.js';
import {ETUDES} from '../etudes/catalog.js';
import './pdfStudio.css';
const PdfPractice=lazy(()=>import('./PdfPractice.jsx'));
const ScoreEditor=lazy(()=>import('../etudes/ScoreEditor.jsx'));
const Lessons=lazy(()=>import('../etudes/EtudeStudio.jsx'));
function readEditableLibrary(){try{return loadLibrary(localStorage,ETUDES);}catch{return {records:{},errors:['편집 악보 저장소를 사용할 수 없습니다.']};}}
const meters=['2/4','3/4','4/4','5/4','6/8','7/8','9/8','12/8'];
export function pdfMetadata(source={}) {
 const count=Math.max(1,Math.floor(Number(source.pageCount)||1));
 return {title:String(source.title||'새 PDF 악보').slice(0,200),artist:String(source.artist??'').slice(0,200),bpm:Math.max(30,Math.min(240,Number(source.bpm)||80)),meter:meters.includes(source.meter?.join('/'))?source.meter:[4,4],difficulty:['미지정','초급','중급','고급'].includes(source.difficulty)?source.difficulty:'미지정',tags:Array.isArray(source.tags)?source.tags.map(String).slice(0,30):[],memo:String(source.memo??'').slice(0,5000),pageCount:count,lastPage:Math.max(1,Math.min(count,Number(source.lastPage)||1)),zoom:source.zoom==='fit'?'fit':Math.max(25,Math.min(250,Number(source.zoom)||100)),mobileZoom:source.mobileZoom==='fit'||source.mobileZoom==null?'fit':Math.max(25,Math.min(250,Number(source.mobileZoom)||100)),barMap:(Array.isArray(source.barMap)?source.barMap:[]).filter(b=>Number.isInteger(b.number)&&b.number>0&&Number.isInteger(b.page)&&b.page>0&&b.page<=count&&[b.x,b.y,b.width,b.height,b.beats].every(Number.isFinite)&&b.x>=0&&b.y>=0&&b.width>0&&b.height>0&&b.x+b.width<=1.001&&b.y+b.height<=1.001&&b.beats>=1&&b.beats<=32).slice(0,5000),practiceOrder:Array.isArray(source.practiceOrder)?source.practiceOrder.filter(Number.isInteger).slice(0,1000):[],countIn:Boolean(source.countIn),audible:source.audible!==false,highlight:Boolean(source.highlight),loop:Boolean(source.loop),loopStart:Math.max(1,Number(source.loopStart)||1),loopEnd:Math.max(1,Number(source.loopEnd)||1)};
}
function MetadataDialog({record,onSave,onClose,busy,error}) {
 const ref=useRef(null),[draft,setDraft]=useState(record);
 useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 const field=(key,value)=>setDraft(d=>({...d,[key]:value}));
 return <dialog ref={ref} className="pdfDialog" aria-label="PDF 악보 정보" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><form onSubmit={e=>{e.preventDefault();onSave(draft);}}><h2>PDF 악보 정보</h2>{error&&<p role="alert">{error}</p>}<label>악보 제목<input autoFocus required maxLength="200" value={draft.title} onChange={e=>field('title',e.target.value)}/></label><label>작곡가 / 아티스트<input maxLength="200" value={draft.artist} onChange={e=>field('artist',e.target.value)}/></label><div className="pdfPair"><label>BPM<input type="number" min="30" max="240" required value={draft.bpm} onChange={e=>field('bpm',e.target.value)}/></label><label>박자<select value={draft.meter.join('/')} onChange={e=>field('meter',e.target.value.split('/').map(Number))}>{meters.map(m=><option key={m}>{m}</option>)}</select></label></div><label>난이도<select value={draft.difficulty} onChange={e=>field('difficulty',e.target.value)}>{['미지정','초급','중급','고급'].map(v=><option key={v}>{v}</option>)}</select></label><label>연습 태그 · 쉼표로 구분<input value={draft.tags.join(',')} onChange={e=>field('tags',e.target.value.split(','))}/></label><label>메모<textarea maxLength="5000" value={draft.memo} onChange={e=>field('memo',e.target.value)}/></label><p>PDF 원본과 설정을 현재 브라우저의 기기에 저장합니다. 서버로 업로드하지 않습니다.</p><footer><button type="button" disabled={busy} onClick={onClose}>취소</button><button type="submit" className="pdfPrimary" disabled={busy}>{busy?'저장 중…':'기기에 저장'}</button></footer></form></dialog>;
}
export default function PdfStudio({mobile,onOpenMenu,onExit}) {
 const [mode,setMode]=useState('pdf'),[records,setRecords]=useState([]),[library,setLibrary]=useState(()=>readEditableLibrary()),[editing,setEditing]=useState(null),[opened,setOpened]=useState(null),[pending,setPending]=useState(null),[remove,setRemove]=useState(null),[duplicate,setDuplicate]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('practice'),[estimate,setEstimate]=useState(null);
 const input=useRef(null),backup=useRef(null),jsonInput=useRef(null);
 const refresh=async()=>{try{setRecords(await listPdfs());setEstimate(await navigator.storage?.estimate?.());}catch(e){setError(storageError(e));}setLibrary(readEditableLibrary());};
 useEffect(()=>{void refresh();},[]);
 const open=async record=>{setBusy(true);setError('');try{const blob=await getPdf(record.id);if(!blob)throw Error('저장된 원본 PDF가 없습니다. 백업 또는 원본을 다시 불러오세요.');setOpened({record,blob});}catch(e){setError(e.message);}finally{setBusy(false);}};
 const importPdf=async e=>{const blob=e.target.files?.[0];e.target.value='';if(!blob)return;setBusy(true);setError('');setMessage('PDF 확인 및 첫 페이지 준비 중…');try{const fingerprint=await fingerprintPdf(blob),existing=await findPdf(fingerprint);if(existing){setDuplicate(existing);setMessage('동일한 PDF가 이미 저장되어 있습니다.');return;}const info=await inspectPdf(blob);const record={...pdfMetadata({title:blob.name.replace(/\.pdf$/i,''),...info,zoom:'fit'}),...info,id:crypto.randomUUID(),fingerprint,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastPracticedAt:null};setPending({record,blob});setMessage('정보를 확인한 후 저장하세요.');}catch(e){setError(e.name==='PasswordException'?'암호를 해제한 PDF 사본을 선택하세요.':e.message);}finally{setBusy(false);}};
 const save=async draft=>{setBusy(true);setError('');try{const record={...draft,...pdfMetadata(draft),updatedAt:new Date().toISOString()};if(pending.blob)await savePdf(record,pending.blob);else await patchPdf(record.id,record);setPending(null);setMessage('PDF 악보를 기기에 저장했습니다.');await refresh();}catch(e){setError(storageError(e));}finally{setBusy(false);}};
 const saveScore=document=>{try{const result=saveLibraryDocument(localStorage,document,ETUDES);if(result.saved)setLibrary(readEditableLibrary());return result;}catch(e){return {saved:false,errors:[e.message]};}};
 const importJson=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>2*1024*1024)throw Error('악보 JSON은 2MB 이하만 지원합니다.');const doc=upgradeDocument(JSON.parse(await f.text()));if(!hasEditableShape(doc))throw Error('악보의 음표·마디 구조를 확인하세요.');setEditing(copyDocument(doc));}catch(e){setError(`악보 불러오기 실패: ${e.message}`);}};
 const restore=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');let added=0,skipped=0;try{for(const {record:old,pdfBlob} of await readBackup(file)){const fingerprint=await fingerprintPdf(pdfBlob);if(await findPdf(fingerprint)){skipped++;continue;}const info=await inspectPdf(pdfBlob),record={...pdfMetadata({...old,pageCount:info.pageCount}),...info,id:crypto.randomUUID(),fingerprint,createdAt:Number.isFinite(Date.parse(old.createdAt))?old.createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastPracticedAt:Number.isFinite(Date.parse(old.lastPracticedAt))?old.lastPracticedAt:null};await savePdf(record,pdfBlob);added++;}setMessage(`${added}개 복원 · 기존과 같은 PDF ${skipped}개 유지`);}catch(e){setError(`${added}개 복원 후 중단. ${storageError(e)}`);}finally{await refresh();setBusy(false);}};
 const filtered=records.filter(r=>`${r.title} ${r.artist} ${r.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ko'):sort==='bpm'?a.bpm-b.bpm:sort==='added'?b.createdAt.localeCompare(a.createdAt):(b.lastPracticedAt??'').localeCompare(a.lastPracticedAt??''));
 const run=async action=>{setBusy(true);setError('');try{await action();}catch(e){setError(storageError(e));}finally{setBusy(false);}};
 const top=<><header className="pdfStudioHeading"><div><span>FRETIVA LAB / SHEET MUSIC</span><h1>PDF 악보 연습실</h1><p>내 악보를 열고, 나의 템포로 연습하세요.</p></div><div><button type="button" className="pdfPrimary" disabled={busy} onClick={()=>input.current.click()}>PDF 불러오기</button><button type="button" onClick={()=>setEditing(createBlankDocument())}>간단 악보 만들기</button></div></header><nav className="pdfStudioTabs"><button type="button" aria-pressed={mode==='pdf'} onClick={()=>setMode('pdf')}>내 악보 보관함</button><button type="button" aria-pressed={mode==='lessons'} onClick={()=>setMode('lessons')}>기존 연습곡 · 에튀드</button></nav></>;
 return <section className={`pdfStudio ${mobile?'pdfStudio--mobile':'pdfStudio--desktop'}`}>
  {mobile&&<nav className="pdfMobileNav"><button type="button" onClick={onExit}>홈 ⌂</button><button type="button" onClick={onOpenMenu}>메뉴 ☰</button></nav>}
  <input ref={input} type="file" accept="application/pdf,.pdf" hidden aria-label="PDF 파일 선택" onChange={importPdf}/><input ref={backup} type="file" accept=".fretiva-pdf" hidden aria-label="PDF 백업 선택" onChange={restore}/><input ref={jsonInput} type="file" accept="application/json,.json" hidden aria-label="편집 악보 JSON 선택" onChange={importJson}/>
  {error&&<p role="alert" className="pdfError">{error}</p>}{message&&!opened&&<p role="status">{message}</p>}
  {opened?<Suspense fallback={<p>PDF 연습실 준비 중…</p>}><PdfPractice key={opened.record.id} initial={opened.record} blob={opened.blob} mobile={mobile} onClose={()=>{setOpened(null);void refresh();}}/></Suspense>:<>{top}{mode==='lessons'?<Suspense fallback={<p>연습곡 준비 중…</p>}><Lessons {...{mobile,onOpenMenu,onExit}}/></Suspense>:<>
   <div className="pdfLibraryTools"><input aria-label="악보 검색" placeholder="제목, 아티스트, 태그 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="악보 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="practice">최근 연습</option><option value="added">최근 추가</option><option value="title">제목순</option><option value="bpm">BPM순</option></select></div>
   {!records.length&&<div className="pdfEmpty"><h2>연습할 PDF 악보를 불러오세요</h2><p>첫 페이지 미리보기와 마지막 연습 위치가 보관함에 남습니다.</p><button type="button" disabled={busy} onClick={()=>input.current.click()}>내 기기에서 PDF 선택</button></div>}
   <div className="pdfCards">{filtered.map(r=><article key={r.id} className="pdfCard"><button type="button" className="pdfThumbnail" disabled={busy} aria-label={`${r.title} 연습하기`} onClick={()=>void open(r)}><img src={r.thumbnail} alt={`${r.title} 첫 페이지`} loading="lazy"/></button><div><small>PDF · {r.difficulty}</small><h2>{r.title}</h2><p>{r.artist}</p><p>{r.bpm} BPM · {r.meter.join('/')} · {r.pageCount}페이지</p><small>마지막 {r.lastPage}페이지 · {r.lastPracticedAt?new Date(r.lastPracticedAt).toLocaleDateString('ko-KR'):'아직 연습 전'}</small><div className="pdfCardActions"><button type="button" disabled={busy} onClick={()=>void open(r)}>연습하기</button><button type="button" disabled={busy} onClick={()=>setPending({record:r})}>정보 수정</button><button type="button" disabled={busy} onClick={()=>void run(async()=>downloadBlob(await getPdf(r.id),`${r.title}.pdf`))}>원본 PDF</button><button type="button" disabled={busy} onClick={()=>setRemove(r)}>삭제</button></div></div></article>)}</div>
   {records.length>0&&!filtered.length&&<p>검색 결과가 없습니다.</p>}
   <section className="pdfEditableLibrary"><h2>간단 악보 · 편집 가능한 FRETIVA 문서</h2><p>오선보와 TAB을 함께 편집합니다. 복잡한 제작은 MuseScore 등의 전문 프로그램을 이용해 주세요.</p><button type="button" onClick={()=>setEditing(createBlankDocument())}>새 악보</button><button type="button" onClick={()=>jsonInput.current.click()}>악보 파일 불러오기</button>{library.errors.map(e=><p role="alert" key={e}>{e}</p>)}{Object.values(library.records).filter(r=>r.document.title.toLowerCase().includes(search.toLowerCase())).map(r=><div key={r.document.id} className="pdfEditableRow"><span>{r.document.title} · {r.status==='saved'?'저장됨':'초안'} · FRETIVA</span><button type="button" disabled={r.status==='unreadable'} onClick={()=>setEditing(r.document)}>열기</button><button type="button" disabled={r.status==='unreadable'} onClick={()=>setEditing(copyDocument(r.document))}>복사해 편집</button></div>)}</section>
   <details className="pdfStorage"><summary>기기 저장 공간 · 백업</summary><p>현재 브라우저의 기기에만 저장됩니다. 브라우저 데이터 삭제·기기 변경 시 사라질 수 있으므로 원본과 백업을 별도로 보관하세요.</p>{estimate&&<p>이 사이트 사용량 {(estimate.usage/1048576).toFixed(1)} MB / 허용량 {(estimate.quota/1048576).toFixed(0)} MB</p>}<button type="button" onClick={()=>void run(async()=>{const granted=await navigator.storage?.persist?.();setMessage(granted?'기기 저장소 유지 요청이 승인되었습니다.':'브라우저가 저장소 유지 요청을 승인하지 않았습니다. 백업을 보관하세요.');})}>저장소 유지 요청</button><button type="button" disabled={busy||!records.length} onClick={()=>void run(async()=>downloadBlob(await exportPdfLibrary(),'FRETIVA-PDF-library.fretiva-pdf'))}>PDF 보관함 백업</button><button type="button" disabled={busy} onClick={()=>backup.current.click()}>PDF 백업 복원</button><p>PDF 백업에는 PDF 원본과 연습 설정이 포함됩니다. 편집 악보는 편집기의 파일 내보내기로 보관합니다.</p></details>
  </>}</>}
  {pending&&<MetadataDialog key={pending.record.id} record={pending.record} {...{busy,error}} onSave={save} onClose={()=>setPending(null)}/>}
  {remove&&<Confirm text={`‘${remove.title}’ PDF 원본·썸네일·마디 설정을 이 기기에서 삭제할까요?`} busy={busy} onCancel={()=>setRemove(null)} onConfirm={()=>void run(async()=>{await deletePdf(remove.id);setRemove(null);setMessage('PDF와 연결된 데이터를 삭제했습니다.');await refresh();})}/>}
  {duplicate&&<Confirm text={`같은 PDF ‘${duplicate.title}’이 이미 있습니다. 기존 악보를 열까요?`} onCancel={()=>setDuplicate(null)} onConfirm={()=>{void open(duplicate);setDuplicate(null);}}/>}
  {editing&&<Suspense fallback={<p>기존 편집기 준비 중…</p>}><ScoreEditor key={editing.id} document={editing} mobile={mobile} onClose={()=>{setEditing(null);void refresh();}} onSave={saveScore} onImportPdf={()=>input.current.click()}/></Suspense>}
 </section>;
}
function Confirm({text,onConfirm,onCancel,busy}) {const ref=useRef(null);useEffect(()=>{ref.current.showModal();},[]);return <dialog className="pdfDialog" ref={ref} aria-label="확인" onCancel={e=>{if(busy)e.preventDefault();else onCancel();}}><p>{text}</p><footer><button type="button" disabled={busy} onClick={onCancel}>취소</button><button type="button" disabled={busy} onClick={onConfirm}>확인</button></footer></dialog>;}
