import EditorChoiceMenu from './EditorChoiceMenu.jsx';
import {DRUM_TECHNIQUES} from './drumTechniques.js';
import {useEffect,useId,useState} from 'react';
import {DRUMS} from './scoreInstruments.js';
import './drumInput.css';
import drumKitImage from './assets/drum-kit.png';
const kit=[['crash','크래시',49],['tom1','탐 1',48],['tom2','탐 2',45],['ride','라이드',51],['hat','하이햇',42],['snare','스네어',38],['kick','킥',36],['floor','플로어 탐',41]];
// Labels and lens centres are anchored to the original image, not the touch boxes.
// Keep distinct extra sounds; GM aliases remain supported for saved scores.
const extraDrums=DRUMS.filter(d=>[37,40,44,53].includes(d.midi));
const faces={crash:[20,18,13,11],tom1:[40,24,7.5,8],tom2:[61,25,8,8],ride:[85,27,13,12],hat:[11.5,43,10,7],snare:[31,54,10,9],kick:[50,60,11,13],floor:[78,54,11,10]};
const zones={crash:[5,1,27,26],tom1:[33,15,17,26],tom2:[53,15,17,26],ride:[71,7,28,30],hat:[1,35,21,26],snare:[23,45,19,26],kick:[43,52,21,46],floor:[66,45,24,25]};
export default function DrumInput({onRest,hat,onHat,batch,onBatch,event,cursor,meter,onEnter,onKey,preview,onPreview,volume,onVolume,onTechnique,onRimshot}){
 const lensId=useId().replaceAll(':','');
 const [open,setOpen]=useState(false),[pressed,setPressed]=useState(new Set());
 const mark=(id,down)=>setPressed(old=>{const n=new Set(old);down?n.add(id):n.delete(id);return n;});
 useEffect(()=>{const clear=()=>setPressed(new Set());window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 const handlers=(id,midi)=>({onPointerDown:e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);mark(id,true);onEnter([midi]);},onPointerMove:e=>{const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)mark(id,false);},onPointerUp:()=>mark(id,false),onPointerCancel:()=>mark(id,false),onLostPointerCapture:()=>mark(id,false),onBlur:()=>mark(id,false),onKeyDown:e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();if(!e.repeat){mark(id,true);onEnter([midi]);}}},onKeyUp:e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();mark(id,false);}},onClick:e=>{if(e.detail===0)onEnter([midi]);}});
 const selected=event.notes.find(n=>n.id===cursor.noteId);
 const techniqueOptions=[...DRUM_TECHNIQUES.slice(0,4),{value:'roll',label:'롤 ▸',options:DRUM_TECHNIQUES.slice(4,8)},DRUM_TECHNIQUES.at(-1)];
 const beat=event.onset/(1920/meter[1])+1,label=Number.isInteger(beat)?String(beat):event.tuplet?`${Math.floor(beat)} + ${Math.round((beat%1)*3)}/3`:String(beat);
 return <div className="drumInputPanel"><div className="drumCursorRow"><button type="button" className="drumNext" aria-label="이전 입력 위치" onClick={()=>onKey('ArrowLeft')}>← 이전</button><output aria-live="polite">{cursor.bar+1}마디 · {label}박</output><button type="button" className="drumNext" aria-label="다음 입력 위치" onClick={()=>onKey('ArrowRight')}>다음 →</button></div><div className="drumEditRow"><button type="button" onClick={onRest}>쉼표</button><button type="button" disabled={!cursor.lowerRest&&!cursor.noteId&&!event.rest} onClick={()=>onKey('Delete')}>선택 삭제</button><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>추가 악기</button></div>
 <div className="drumHatRow"><span>하이햇</span><button type="button" role="switch" aria-label="하이햇 열림" aria-checked={hat==='open'} className="drumBatchSwitch drumHatSwitch" onClick={()=>onHat(hat==='open'?'closed':'open')}><span>닫힘</span><span>열림</span><i aria-hidden="true"/></button><span className="drumBatchLabel">일괄</span><button type="button" role="switch" aria-label="하이햇 일괄 입력" aria-checked={batch} className="drumBatchSwitch" onClick={()=>onBatch(!batch)}><span>OFF</span><span>ON</span><i aria-hidden="true"/></button><EditorChoiceMenu label="드럼 주법" triggerLabel="주법" value="" selectedValues={Object.values(selected?.drumTechnique??{})} disabled={!selected||event.rest} options={techniqueOptions} onChange={onTechnique}/><button type="button" className="drumPreviewToggle" aria-label="드럼 입력 소리" aria-pressed={preview} onClick={()=>onPreview(!preview)}>소리 {preview?'켬':'끔'}</button></div>
 <div className="drumKit drumKitPhoto" role="group" aria-label="드럼 그림 입력"><img className="drumKitImage" src={drumKitImage} alt="" draggable="false"/><svg className="drumHitLens" viewBox="0 0 1536 1024" aria-hidden="true">{kit.filter(([id])=>pressed.has(id)).map(([id])=>{const [x,y,rx,ry]=faces[id],cx=x*15.36,cy=y*10.24;return <g key={id}><defs><clipPath id={lensId+id}><ellipse cx={cx} cy={cy} rx={rx*15.36} ry={ry*10.24}/></clipPath></defs><g clipPath={`url(#${lensId+id})`}><image href={drumKitImage} width="1536" height="1024" transform={`translate(${cx} ${cy}) scale(1.07) translate(${-cx} ${-cy})`}/></g></g>;})}</svg>{kit.map(([id,label,base])=>{const midi=id==='hat'&&hat==='open'?46:base;return <button type="button" key={id} className={'drumPiece drum-'+id} style={{'--label-x':((faces[id][0]-zones[id][0])/zones[id][2]*100)+'%','--label-y':((faces[id][1]-zones[id][1])/zones[id][3]*100)+'%'}} aria-label={id==='hat'?`하이햇 ${hat==='open'?'열림':'닫힘'}`:label} aria-pressed={pressed.has(id)} data-entered={event.notes.some(n=>n.midi===midi)} {...handlers(id,midi)}><span>{label}</span></button>;})}</div>
 {open&&<div className="drumExtra" role="group" aria-label="추가 타악기">{extraDrums.map(d=><button type="button" key={d.midi} aria-label={d.label} aria-pressed={pressed.has(d.midi)} data-entered={event.notes.some(n=>n.midi===d.midi)} {...handlers(d.midi,d.midi)}>{d.label}</button>)}<button type="button" aria-label="림샷 (합성)" data-entered={event.notes.some(n=>n.drumArticulation==='rimshot')} onClick={onRimshot}>림샷 (합성)</button></div>}

<label className="drumVolume">음량<input type="range" min="0" max="1" step=".05" aria-label="드럼 음량" value={volume} onChange={e=>onVolume(Number(e.target.value))}/></label></div>;
}
