import { localizeUi } from "../i18n/core.js";
import ko from "./../i18n/locales/ko.js";
import { t as translateUi } from "./../i18n/core.js";
import { Translation, useLanguage } from "./../i18n/react.jsx";
import {useEffect,useState} from 'react';
import {scoreInstrument} from './scoreInstruments.js';
import {midiName} from './scoreTuning.js';
import './keyboardInput.css';
function HandKeyboard({hand,onEnter,instrument}){
  useLanguage();
 const handName=hand==='right'?ko["etudes.rightHand"]:ko["etudes.leftHand"];
 const [octave,setOctave]=useState(hand==='right'?4:3),[pressed,setPressed]=useState(new Set());
 const profile=scoreInstrument(instrument);
 const press=(midi,down)=>setPressed(old=>{const next=new Set(old);down?next.add(midi):next.delete(midi);return next;});
 useEffect(()=>{const clear=()=>setPressed(new Set());window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 return <section className="pianoHandInput" aria-label={handName+translateUi("etudes.input")}><div className="scorePitchToolbar pianoRangeRow"><strong>{localizeUi(handName)}</strong><button type="button" aria-label={handName+translateUi("etudes.lowerOctave")} disabled={octave<=-1} onClick={()=>setOctave(v=>v-1)}>−</button><span><Translation id="originalUi.cKeyboardinput" />{octave}<Translation id="originalUi.b" />{octave}</span><button type="button" aria-label={handName+translateUi("etudes.higherOctave")} disabled={octave>=9} onClick={()=>setOctave(v=>v+1)}>＋</button></div>
   <div className="scorePianoKeys" role="group" aria-label={translateUi("etudes.value1Key", { value1: handName })}>{Array.from({length:12},(_,pc)=>{const midi=(octave+1)*12+pc,black=[1,3,6,8,10].includes(pc);return <button type="button" key={midi} className={black?'black-key':'white-key'} aria-label={midiName(midi)} aria-pressed={pressed.has(midi)} disabled={midi<(profile.minMidi??0)||midi>(profile.maxMidi??127)} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);press(midi,true);onEnter([midi],hand);}} onPointerMove={e=>{const b=e.currentTarget.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)press(midi,false);}} onPointerUp={()=>press(midi,false)} onPointerCancel={()=>press(midi,false)} onLostPointerCapture={()=>press(midi,false)} onPointerLeave={()=>press(midi,false)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();if(!e.repeat){press(midi,true);onEnter([midi],hand,{focus:false});}}}} onKeyUp={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();press(midi,false);}}} onBlur={()=>press(midi,false)} onClick={e=>{if(e.detail===0)onEnter([midi],hand);}}>{midiName(midi)}</button>;})}</div></section>;
}
export default function KeyboardInput({renderControls,hand,instrument,event,cursor,desktop,onEnter,onKey,onHand,chordMode,onChordMode}){
  useLanguage();
 return <div className={'scorePitchInput pianoDualInput '+(desktop?'is-desktop':'is-mobile')}>{renderControls?renderControls(<div className="pianoMobileActions"><button type="button" aria-label={translateUi("etudes.chordInput")} aria-pressed={chordMode} onClick={()=>onChordMode(!chordMode)}><Translation id="etudes.chord" /></button><button type="button" onClick={()=>onKey('r')}><Translation id="etudes.rest" /></button><button type="button" aria-label={translateUi("etudes.deleteSelectedNote")} disabled={!cursor.noteId&&!event.rest} onClick={()=>onKey('Delete')}><Translation id="app.deleteSelected" /></button></div>):<div className="scorePitchToolbar pianoEntryControls"><button type="button" aria-label={translateUi("etudes.chordInput")} aria-pressed={chordMode} onClick={()=>onChordMode(!chordMode)}><Translation id="etudes.chord" /></button><button type="button" aria-label={translateUi("etudes.previousInputPosition")} onClick={()=>onKey('ArrowLeft')}>←</button><output>{hand==='left'?translateUi("etudes.leftHand"):translateUi("etudes.rightHand")} · {cursor.bar+1}<Translation id="app.barApp" />{event.onset/480+1}<Translation id="app.beat" /></output><button type="button" aria-label={translateUi("etudes.nextInputPosition")} onClick={()=>onKey('ArrowRight')}>→</button><button type="button" onClick={()=>onKey('r')}><Translation id="etudes.rest" /></button></div>}{['right','left'].map(hand=><HandKeyboard key={hand} {...{hand,instrument,onEnter}}/>)}{cursor.noteId&&<div className="scorePitchToolbar"><span><Translation id="etudes.selectedNote" /></span><button type="button" onClick={()=>onKey('Delete')}><Translation id="common.delete" /></button><button type="button" disabled={hand==='left'} onClick={()=>onHand('left')}><Translation id="etudes.moveToLeftHandStaff" /></button><button type="button" disabled={hand==='right'} onClick={()=>onHand('right')}><Translation id="etudes.moveToRightHandStaff" /></button></div>}</div>;
}
