import {useEffect,useState} from 'react';
import {scoreInstrument} from './scoreInstruments.js';
import {midiName} from './scoreTuning.js';
import './keyboardInput.css';
function HandKeyboard({hand,onEnter,instrument}){
 const handName=hand==='right'?'오른손':'왼손';
 const [octave,setOctave]=useState(hand==='right'?4:3),[pressed,setPressed]=useState(new Set());
 const profile=scoreInstrument(instrument);
 const press=(midi,down)=>setPressed(old=>{const next=new Set(old);down?next.add(midi):next.delete(midi);return next;});
 useEffect(()=>{const clear=()=>setPressed(new Set());window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 return <section className="pianoHandInput" aria-label={handName+' 입력'}><div className="scorePitchToolbar pianoRangeRow"><strong>{handName}</strong><button type="button" aria-label={handName+' 낮은 옥타브'} disabled={octave<=-1} onClick={()=>setOctave(v=>v-1)}>−</button><span>C{octave}–B{octave}</span><button type="button" aria-label={handName+' 높은 옥타브'} disabled={octave>=9} onClick={()=>setOctave(v=>v+1)}>＋</button></div>
   <div className="scorePianoKeys" role="group" aria-label={`${handName} 건반`}>{Array.from({length:12},(_,pc)=>{const midi=(octave+1)*12+pc,black=[1,3,6,8,10].includes(pc);return <button type="button" key={midi} className={black?'black-key':'white-key'} aria-label={midiName(midi)} aria-pressed={pressed.has(midi)} disabled={midi<(profile.minMidi??0)||midi>(profile.maxMidi??127)} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);press(midi,true);onEnter([midi],hand);}} onPointerMove={e=>{const b=e.currentTarget.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)press(midi,false);}} onPointerUp={()=>press(midi,false)} onPointerCancel={()=>press(midi,false)} onLostPointerCapture={()=>press(midi,false)} onPointerLeave={()=>press(midi,false)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();if(!e.repeat){press(midi,true);onEnter([midi],hand,{focus:false});}}}} onKeyUp={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();press(midi,false);}}} onBlur={()=>press(midi,false)} onClick={e=>{if(e.detail===0)onEnter([midi],hand);}}>{midiName(midi)}</button>;})}</div></section>;
}
export default function KeyboardInput({hand,instrument,event,cursor,desktop,onEnter,onKey,onHand,chordMode,onChordMode}){
 return <div className={'scorePitchInput pianoDualInput '+(desktop?'is-desktop':'is-mobile')}><div className="scorePitchToolbar pianoEntryControls"><button type="button" aria-label="화음 입력" aria-pressed={chordMode} onClick={()=>onChordMode(!chordMode)}>화음</button><button type="button" aria-label="이전 입력 위치" onClick={()=>onKey('ArrowLeft')}>←</button><output>{hand==='left'?'왼손':'오른손'} · {cursor.bar+1}마디 · {event.onset/480+1}박</output><button type="button" aria-label="다음 입력 위치" onClick={()=>onKey('ArrowRight')}>→</button><button type="button" onClick={()=>onKey('r')}>쉼표</button></div>{['right','left'].map(hand=><HandKeyboard key={hand} {...{hand,instrument,onEnter}}/>)}{cursor.noteId&&<div className="scorePitchToolbar"><span>선택 음</span><button type="button" onClick={()=>onKey('Delete')}>삭제</button><button type="button" disabled={hand==='left'} onClick={()=>onHand('left')}>왼손 보표로</button><button type="button" disabled={hand==='right'} onClick={()=>onHand('right')}>오른손 보표로</button></div>}</div>;
}
