// Shared guide content; the desktop dialog owns its navigation and layout.
const text=(ko,en,audience)=>({ko,en,audience});
const topics=[
 {id:'tab-repeat',audience:'fretted',keywords:'스트럼 운지 생략 슬래시 strum slash repeat',title:text('반복 운지 생략','Repeated-fret slashes'),intro:text('같은 코드를 반복해서 칠 때 숫자 대신 /와 리듬을 표시합니다. 실제 운지와 재생은 유지됩니다.','Show repeated chords with rhythm slashes while retaining all frets and playback.'),blocks:[
  {title:text('현재 마디 또는 선택 구간에 적용','Apply to a bar or selected range'),steps:[text('첫 운지를 입력하고 줄 복사 등으로 반복할 음을 만듭니다. 각 위치의 길이와 다운·업을 설정합니다.','Enter a grip and duplicate it with Copy line or other copy tools. Set each duration and down/up stroke.'),text('여러 마디에 적용하려면 악보를 드래그하여 구간을 선택합니다. 선택 구간이 없으면 현재 마디에 적용됩니다.','Drag across the score to select multiple bars. Without a selection, the current bar is used.'),text('상단의 반복 운지 생략을 누릅니다. 다시 누르면 숫자를 복원합니다. 실행 취소도 가능합니다.','Click Hide repeated frets in the top toolbar. Click again to restore numbers, or use Undo.')],tip:text('마디의 첫 코드, 운지가 바뀐 곳, 쉼표 뒤에는 숫자를 표시합니다. 단음·뮤트·미확정 운지·연결 주법은 생략하지 않습니다.','The first chord of each bar, changed grips and chords after rests retain numbers. Single notes, muted or unresolved grips and connecting techniques are not omitted.')}
 ]},
 {id:'start',title:text('처음 입력하기','Enter your first notes'),intro:text('음 길이 → 악보의 위치 → 프렛 숫자 순서로 입력합니다.','Choose a duration, select a score position, then enter a fret.'),audience:'fretted',blocks:[
  {title:text('8분음표 네 개 입력하기','Enter four eighth notes'),steps:[text('상단에서 8분음표를 선택하고, 악보에서 입력할 줄과 위치를 클릭합니다.','Select the eighth-note button, then click a string and position in the score.'),text('숫자 3을 입력합니다. 숫자 입력 후에는 같은 위치에 머뭅니다.','Type 3. Fret input stays at the current position.'),text('→로 다음 위치에 이동한 뒤 5를 입력합니다. 같은 방식으로 7, 5를 입력합니다.','Press →, then type 5. Repeat for 7 and 5.'),text('아래 재생 버튼으로 음과 리듬을 확인합니다.','Use Play below to check the notes and rhythm.')],sequence:['3','→','5','→','7','→','5']},
  {title:text('화음과 두 자리 프렛','Chords and two-digit frets'),body:text('화음은 같은 위치에서 ↑·↓로 줄만 바꾸어 숫자를 입력합니다. 12프렛은 1, 2를 차례로 누릅니다. 입력 시간 제한은 없으며, 다른 위치를 선택하면 새 숫자 입력을 시작합니다.','For a chord, stay at the same position and use ↑ or ↓ to change strings before entering each fret. Type 1 then 2 for fret 12. There is no timeout; selecting a different position starts a new number.'),tip:text('다음 음을 쓰려면 먼저 →를 누르세요. 같은 자리에서 3 다음 5를 누르면 새 음으로 이동하지 않습니다.','Press → before entering the next note. Typing 3 then 5 at the same position does not move to a new note.')}
 ]},
 {id:'start',title:text('피아노 입력하기','Enter piano notes'),intro:text('음 길이와 손을 선택한 뒤 오른쪽 건반으로 입력합니다.','Choose a duration and hand, then use the keyboard panel.'),audience:'piano',blocks:[
  {title:text('멜로디와 화음','Melody and chords'),steps:[text('음 길이를 선택하고 악보에서 시작 위치를 선택합니다.','Choose a duration and a starting position in the score.'),text('오른손·왼손을 선택하고 건반을 누릅니다. 일반 입력은 다음 위치로 이동합니다.','Choose the right or left hand and press a key. Normal input advances to the next position.'),text('화음 모드에서는 같은 위치에 음을 모은 뒤 →로 다음 위치로 이동합니다.','In chord mode, collect notes at one position, then press → to continue.'),text('연결한 MIDI 건반 설정은 악보 위 편집 버튼에서 열 수 있습니다.','Open Edit above the score to configure a connected MIDI keyboard.')]}
 ]},
 {id:'start',title:text('드럼 입력하기','Enter drum notes'),intro:text('오른쪽 드럼 패드에서 소리를 선택하여 리듬을 만듭니다.','Use the drum pads on the right to build a rhythm.'),audience:'drums',blocks:[
  {title:text('한 위치에 드럼 쌓기','Layer drum hits'),steps:[text('음 길이를 선택하고 악보에서 입력할 위치를 클릭합니다.','Choose a duration and click a position in the score.'),text('킥·스네어·하이햇 패드를 눌러 같은 위치에 함께 넣습니다. 같은 패드를 다시 누르면 해당 음이 지워집니다.','Press kick, snare and hi-hat pads to layer hits. Pressing the same pad again removes that hit.'),text('→로 다음 위치에 이동해 입력합니다. 재생으로 리듬을 확인합니다.','Press → to continue at the next position. Use Play to check the rhythm.')],tip:text('행 전체 입력을 켜면 한 음이 아니라 해당 행에 적용됩니다. 개별 입력 중에는 이 설정을 확인하세요.','With whole-row input enabled, a pad affects its row. Check this setting when entering individual hits.')}
 ]},
 {id:'rhythm',keywords:'점음표 점8분 부점 32분 6연음 dotted rest triplet sextuplet 셋잇단음 쉼표',title:text('길이·쉼표·연음','Durations, rests and tuplets'),intro:text('음표 버튼은 길이를 정합니다. 점과 3·6은 길이를 바꾸는 별도 설정입니다.','Note buttons choose duration. The dot, 3 and 6 modify that duration.'),blocks:[
  {title:text('4/4에서 길이 읽기','Read durations in 4/4'),rows:[text(['온음표','4박'],['Whole','4 beats']),text(['2분 / 4분','2박 / 1박'],['Half / quarter','2 beats / 1 beat']),text(['8분 / 16분','½박 / ¼박'],['Eighth / sixteenth','½ beat / ¼ beat']),text(['점8분 + 16분','¾박 + ¼박 = 1박'],['Dotted eighth + sixteenth','¾ beat + ¼ beat = 1 beat'])]},
  {title:text('점은 쉼표가 아닙니다','A dot is not a rest'),body:text('점(·)은 원래 음 길이의 절반을 더합니다. 8분음표와 점을 선택하면 점8분음표입니다. TAB의 점은 빔 쪽에 표시됩니다. 소리를 쉬려면 길이를 고른 뒤 쉼표 버튼이나 R을 사용하세요.','A dot adds half the original duration. Select an eighth note and the dot for a dotted eighth. In rhythmic TAB, the dot appears near the beam. To create silence, choose a duration and use Rest or R.'),tip:text('점을 짧게 누르면 한 번 적용하고, 길게 누르면 연속 입력을 고정합니다. 고정 상태에서는 다시 눌러 해제하세요.','Click the dot for one entry; hold it to lock dotted entry. Click again to turn the lock off.')},
  {title:text('32분음표와 6연음','Thirty-second notes and sextuplets'),body:text('32분음표 하나는 ⅛박입니다. 4/4 한 마디에는 32개가 들어갑니다. 3은 같은 길이 두 개의 시간에 세 음, 6은 네 개의 시간에 여섯 음을 넣습니다. 예를 들어 16분음표와 6을 고르면 여섯 음이 한 박입니다.','A thirty-second note lasts ⅛ beat; 32 fill a 4/4 bar. The 3 button fits three notes into the time of two, and 6 fits six into the time of four. Six sixteenth-note sextuplets fill one quarter-note beat.'),tip:text('촘촘한 모바일 악보는 한 줄 1마디로 보면 숫자 크기를 유지한 채 가로로 이동할 수 있습니다.','In the mobile editor, choose one bar per row to scroll dense music horizontally at a readable fret size.')},
  {title:text('16분 셋잇단음 5–7–5','A sixteenth-note triplet: 5–7–5'),audience:'fretted',steps:[text('빈 위치에서 16분음표와 3 버튼을 선택합니다.','At an empty position, select a sixteenth note and the 3 button.'),text('5를 입력하고 →, 7을 입력하고 →, 5를 입력합니다.','Enter 5, press →, enter 7, press →, and enter 5.'),text('세 음을 채우면 셋잇단음 입력이 끝납니다. 세 개의 16분 셋잇단음은 8분음표 하나의 길이입니다.','Entry finishes when all three notes are filled. Three sixteenth-note triplets occupy one eighth note.')],tip:text('미완성 셋잇단음은 빈 자리를 음이나 쉼표로 채우세요. 없애려면 셋잇단음 중 한 음을 선택하고 상단 3 ▾에서 묶음 삭제를 사용합니다.','Fill unfinished triplets with notes or rests. Select a triplet note, then use Delete group under 3 ▾ to remove the group.')}
 ]},
 {id:'ties',keywords:'붙임줄 타이 Tie hammer-on pull-off slide legato 아르페지오',title:text('Tie·해머온·풀오프','Ties, hammer-ons and pull-offs'),audience:'fretted',intro:text('Tie는 같은 음을 이어 울리고, H·P·SL은 다른 프렛의 음으로 연결합니다.','A tie sustains the same pitch; H, P and SL connect different frets.'),blocks:[
  {title:text('8분음표 뒤, 16분음 첫 칸을 이어 울리기','Sustain an eighth note into the first sixteenth'),steps:[text('먼저 8분음표를 입력합니다.','Enter the eighth note first.'),text('→로 바로 다음 빈 위치에 가서 16분음표를 선택합니다.','Press → to reach the next empty position and select a sixteenth note.'),text('숫자를 입력하지 않고 Tie 버튼 또는 T를 누릅니다. 앞 음의 높이가 이어집니다.','Press Tie or T without entering a fret. The previous pitch continues.'),text('→로 이동해 나머지 16분음표들을 입력합니다.','Press → and enter the remaining sixteenth notes.')],sequence:text(['8분 음','→','16분 선택','Tie','→','다음 음'],['Eighth note','→','Sixteenth','Tie','→','Next note']),tip:text('TAB에서 이어지는 자리의 프렛 숫자는 숨겨져도 음 길이는 차지합니다. 쉼표로 만들면 소리가 끊깁니다. 같은 자리에서 Tie를 다시 누르면 연결을 해제합니다.','The tied continuation takes time even when its TAB fret is hidden. A rest would stop the sound. Press Tie again at that position to remove the connection.')},
  {title:text('H·P·SL 넣기','Add H, P or SL'),body:text('같은 줄에 출발음과 도착음을 먼저 입력합니다. 출발음을 선택하고 주법 메뉴에서 해머온(H), 풀오프(P), 슬라이드(SL)를 고릅니다. 예: 5→7은 H, 7→5는 P. 5–7–5라면 첫 5에 H, 7에 P를 적용합니다.','Enter the start and destination on the same string. Select the starting note and choose Hammer-on (H), Pull-off (P) or Slide (SL) in Techniques. For 5–7–5, apply H to the first 5 and P to 7.')},
  {title:text('화음을 순서대로 울리는 아르페지오','Roll a chord'),body:text('같은 위치에 화음의 프렛들을 입력한 뒤 주법의 아르페지오 방향을 고릅니다. 상승은 낮은음 쪽 줄부터 높은음 쪽으로, 하강은 반대로 재생합니다.','Enter the chord frets at one position, then choose the arpeggio direction in Techniques. Ascending rolls from lower to higher strings; descending reverses the order.')}
 ]},
 {id:'selection',keywords:'드래그 구간 선택 복사 붙여넣기 마디 drag select copy paste insert split',title:text('선택·복사·박 편집','Select, copy and edit beats'),intro:text('클릭은 한 위치를, 드래그는 여러 위치의 구간을 선택합니다.','Click to select one position; drag to select a range.'),blocks:[
  {title:text('구간을 복사해 붙여넣기','Copy and paste a range'),steps:[text('악보에서 시작 위치부터 끝 위치까지 드래그합니다. 선택 영역에 색이 표시됩니다.','Drag across the score from the first position to the last. The selected range is highlighted.'),text('Ctrl+C를 누릅니다. 도착 위치를 클릭하고 Ctrl+V로 붙여넣습니다.','Press Ctrl+C. Click the destination and press Ctrl+V.'),text('실수했으면 Ctrl+Z로 되돌립니다. 선택 영역만 해제하려면 Esc를 누릅니다.','Use Ctrl+Z to undo. Press Esc to clear only the range selection.')],tip:text('구간 복사는 해당 시간의 모든 음을 포함합니다. 마디를 통째로 추가하며 복사하려면 악보 위 편집 → 마디 복사 · 붙여넣기를 이용하세요.','Range copying includes every note at the selected times. To insert copies of complete bars, use Edit above the score → Copy and paste bars.')},
  {title:text('음 옮기기와 박 사이에 자리 만들기','Move notes and make room'),audience:'fretted',body:text('음 이동은 Alt를 누른 채 음표나 TAB 숫자를 드래그합니다. 좌우 이동은 같은 길이의 빈자리로 가능합니다. 사이에 자리가 필요하면 악보 위 편집에서 앞/뒤에 박 삽입 또는 현재 박 나누기를 사용하세요.','Hold Alt while dragging a note or TAB fret to move it. Horizontal movement needs an empty slot of the same duration. Use Edit above the score to insert a slot before/after or split the current duration.'),tip:text('박 삽입은 뒤쪽 위치를 밀기 때문에 마디가 넘칠 수 있습니다. 박 나누기는 선택한 길이를 반으로 나누어 자리를 만듭니다.','Inserting a slot shifts later positions and may overfill the bar. Splitting divides the selected duration in half.')},
  {title:text('줄 복사와 줄 삭제','Copy or delete a vertical group'),body:text('오른쪽 줄 복사는 현재 위치의 운지 묶음을 다음 위치로 복사합니다. 줄 삭제는 현재 위치의 음들을 지우되 길이는 유지합니다. 악보 한 단 전체를 뜻하는 버튼은 아닙니다.','Copy group on the right copies the current vertical note group to the next position. Delete group clears its notes while keeping the duration. These controls do not refer to a whole system of bars.'),audience:'fretted'}
 ]},
 {id:'picking',title:text('피킹·빔·반복','Picking, beams and repeats'),intro:text('악보 오른쪽의 도구에서 표시와 연주 방법을 설정합니다.','Use the tools beside the score for notation and performance settings.'),blocks:[
  {title:text('리듬 기준과 음 순서 교대','Rhythm grid and note alternation'),audience:'fretted',body:text('데스크톱 기본값인 리듬 기준 · 자동은 마디마다 필요한 8·16분 등의 단위를 고르고 음의 박자 위치로 방향을 정합니다. 8분 기준에서 정박은 다운, &는 업입니다. 16분 기준은 1 e & a에 다운 업 다운 업이므로 &도 다운입니다. 쉼표 뒤 첫 음도 엇박이면 업이 될 수 있습니다.','The desktop default, Rhythm grid · Auto, chooses an eighth, sixteenth or finer grid per bar and uses onset time. On an eighth grid, numbered beats are down and & is up. On a sixteenth grid, 1 e & a maps to down up down up, including down on &. An offbeat entrance after a rest can still be up.'),tip:text('음 순서 교대는 실제로 치는 음마다 번갈아 표시합니다. 마디마다·박마다·마디와 쉼표 뒤·계속 교대 중 다시 시작 기준을 고를 수 있습니다. 셋잇단음은 이 방식이나 직접 입력을 사용하세요.','Alternate notes switches direction for each attack. Restart every bar, every beat, after bars and rests, or continue across bars. Use this mode or manual marks for tuplets.')},
  {title:text('피킹을 한 번에 적용하기','Apply a picking pattern'),audience:'fretted',steps:[text('시작할 마디를 클릭하고 아래 피킹 버튼을 엽니다.','Click the starting bar and open Picking.'),text('적용 범위를 전체 악보, 현재 마디, 현재 마디부터 지정 마디까지 중에서 고릅니다.','Choose the whole score, current bar, or current bar through a specified end bar.'),text('다운·업 반복 등 패턴을 고르고 피킹 패턴 적용을 누릅니다. 구간 지정은 끝 마디도 선택합니다.','Choose a pattern and press Apply picking pattern. For a range, also select the end bar.')],tip:text('피킹 범위는 마디 단위입니다. 드래그로 칠한 구간과 별도입니다. H/P/SL 도착음 생략을 켜면 연결음은 다시 피킹하지 않도록 표시합니다.','Picking scope uses whole bars and is separate from the dragged selection. Enable skipping H/P/SL destinations to omit picking marks on connected notes.')},
  {title:text('빔과 반복 표시','Beams and repeat marks'),body:text('빔표기에서 리듬 표시 위치와 빔 연결을 조절합니다. 반복에서는 현재 마디의 반복 시작·끝, 반복 횟수와 이동 기호를 설정합니다. 실제 음 길이는 상단 음표 버튼으로 바꿉니다.','Use Beams to adjust rhythmic display and connections. Use Repeats for start/end repeats, repeat counts and navigation signs on the current bar. Change actual durations with the note buttons at the top.')}
 ]},
 {id:'settings',title:text('제목·박자·화면 설정','Title, meter and display'),intro:text('제목을 누르면 곡 설정이 열립니다. 음과 마디 설정은 주법·편집 도구에서 찾을 수 있습니다.','Click the title for score settings. Find note and bar settings in Techniques and Edit.'),blocks:[
  {title:text('필요한 설정 찾기','Find a setting'),rows:[text(['제목·BPM·연습 메모','악보 제목 클릭'],['Title, BPM and practice notes','Click the score title']),text(['박자·조표','선택 속성 · 악보 위 편집 → 마디 복사 · 붙여넣기 · 악보 설정'],['Meter and key signature','Click the score title → Meter and key']),text(['운지 번호','주법 → 운지 표시'],['Fingerings','Techniques → Fingerings'],'fretted'),text(['튜닝 / 카포','상단 튜닝 버튼 / 악보 위 카포 버튼'],['Tuning / capo','Tuning at the top / Capo above the score'],'fretted'),text(['한 줄의 마디 수 / 줄바꿈','악보 위 1·2·3·4 / 편집 → 줄바꿈 편집'],['Bars per line / line breaks','1–4 above the score / Edit → Line breaks']),text(['실행 취소·다시 실행 / 확대','악보 위 오른쪽 화살표 / 배율'],['Undo, redo / zoom','Arrows above the score / Zoom'])]},
  {title:text('음이 사라진 것처럼 보일 때','When notes seem to disappear'),body:text('TAB·오선보+TAB·오선보는 같은 음을 다른 방식으로 보여줍니다. 카포나 튜닝을 바꿀 때는 음높이 유지와 운지 유지 중 원하는 방식을 고르세요. 바꾸기 전후의 소리와 프렛을 확인할 수 있습니다.','TAB, staff+TAB and staff display the same notes differently. When changing capo or tuning, choose whether to preserve pitches or fingerings, and review the result.'),audience:'fretted'}
 ]},
 {id:'save',title:text('저장·불러오기·PDF','Save, open and export PDF'),intro:text('계속 편집할 악보는 브라우저에 저장하고, 인쇄하거나 공유할 때 PDF로 저장합니다.','Save in the browser to keep editing; export PDF for printing or sharing.'),blocks:[
  {title:text('작업을 보관하는 순서','Keep your work'),steps:[text('이 브라우저에 저장을 누르고 제목과 곡 정보를 확인한 뒤 저장합니다. Ctrl+S로도 열 수 있습니다.','Click Save in this browser, check the title and details, then save. Ctrl+S opens the same dialog.'),text('다시 편집할 때는 제작 악보 불러오기에서 저장한 악보를 고릅니다.','Choose a saved score from Open created scores to continue editing.'),text('원본과 별개로 보관하려면 이 브라우저에 저장 창의 다른 이름으로 저장 · 복사본을 사용합니다.','To keep a separate version, use Save as copy in the Save in this browser dialog.')]},
  {title:text('PDF로 내보내기','Export a PDF'),body:text('오른쪽 도구 영역의 PDF 저장을 누릅니다. 미리보기에서 출력 제목·설명·페이지를 확인한 뒤 PDF 저장을 누르세요. PDF 저장만으로 브라우저의 편집본이 저장되지는 않습니다.','Click PDF save in the tool column on the right. Check the title, descriptions and pages in the preview, then save the PDF. Exporting a PDF does not save the editable browser copy.'),tip:text('브라우저 저장은 현재 브라우저에 보관됩니다. 장기 보관이나 다른 기기로 이동할 때는 악보연습실의 기기 저장 · 백업도 이용하세요.','Browser saves belong to this browser. Use device storage / backup in the practice room for long-term storage or transfer.')}
 ]},
 {id:'shortcuts',title:text('단축키 모아보기','Keyboard shortcuts'),intro:text('악보나 편집 도구에 포커스가 있을 때 사용합니다. 제목·검색 입력 중에는 문자 입력이 우선합니다. Mac에서는 Ctrl 대신 ⌘도 사용할 수 있습니다.','Use these while the score or its tools have focus. Text fields keep normal typing. On Mac, ⌘ also works for Ctrl shortcuts.'),blocks:[
  {title:text('공통 편집','Common editing'),keys:[['← / →',text('이전 / 다음 위치','Previous / next position')],['R',text('쉼표 입력','Enter a rest')],['Delete / Backspace',text('선택한 음 삭제','Delete the selected note')],['+ / −',text('입력 음 길이를 짧게 / 길게','Shorter / longer entry duration')],['Ctrl+C / Ctrl+V',text('구간 복사 / 현재 위치에 붙여넣기','Copy range / paste at the cursor')],['Ctrl+Z',text('실행 취소','Undo')],['Ctrl+Shift+Z / Ctrl+Y',text('다시 실행','Redo')],['Ctrl+S',text('브라우저 저장 창','Open browser save')],['Esc',text('구간 선택 해제 / 열린 창 닫기','Clear selection / close the open dialog')]]},
  {title:text('TAB 입력','TAB entry'),audience:'fretted',keys:[['0–9',text('현재 줄의 프렛 입력','Enter a fret on the current string')],['↑ / ↓',text('줄 이동','Change strings')],['X',text('뮤트 음 입력','Enter a dead note')],['T',text('붙임줄(Tie) 설정 / 해제','Toggle a tie')],['H',text('다음 프렛에 따라 해머온 / 풀오프','Hammer-on / pull-off based on the next fret')],['S',text('슬라이드 설정 / 해제','Toggle slide')],['Alt + ↑ / ↓',text('같은 음높이를 다른 줄 운지로 이동','Move to another string with the same pitch')],['Tab',text('악보 입력 중 오선보 / TAB 커서 전환','Switch staff / TAB cursor from the score')],['Alt + drag',text('음 이동 (일반 드래그는 구간 선택)','Move a note (ordinary dragging selects a range)')]]}
 ]},
 {id:'trouble',title:text('자주 막히는 부분','Troubleshooting'),intro:text('원하는 입력과 다르게 보일 때 먼저 확인할 항목입니다.','Check these when entry behaves differently than expected.'),blocks:[
  {title:text('다음 숫자가 같은 자리를 덮어요','The next number overwrites this position'),body:text('프렛 입력은 자동 이동하지 않습니다. 다음 음 앞에 →를 누르거나 다음 위치를 클릭하세요. 화음은 이 동작을 이용해 같은 위치에 여러 줄을 입력합니다.','Fret input does not advance automatically. Press → or click the next position before typing the next note. This also lets you stack chord notes at one position.'),audience:'fretted'},
  {title:text('16분음표 첫 칸에 숫자가 없어요','The first sixteenth has no fret'),body:text('앞 음과 붙임줄로 이어지는 자리인지 확인하세요. 그 경우 빈 쉼표가 아니라 앞 음의 지속 시간입니다. Tie 도움말의 예제대로 이어지는 칸을 먼저 만들어야 뒤 음의 위치가 맞습니다.','Check whether it is tied from the preceding note. If so, it continues that note rather than resting. Follow the Tie example to reserve its duration before entering later notes.'),audience:'fretted'},
  {title:text('재생이 안 되거나 마디 길이가 넘쳐요','Playback is disabled or a bar is too long'),body:text('화면의 입력 검토를 열어 문제 위치를 확인하세요. 박 삽입으로 마디가 길어졌거나 셋잇단음이 미완성일 수 있습니다. 해당 위치의 길이를 조정하거나 미완성 그룹을 채운 뒤 다시 재생하세요.','Open Input review to locate the issue. Inserted beats may overfill a bar, or a triplet may be incomplete. Adjust durations or complete the group before playing.')},
  {title:text('피킹이 생각한 구간과 다르게 적용돼요','Picking affects a different range'),body:text('피킹 메뉴의 적용 범위와 현재 선택 마디를 확인하세요. 마우스 드래그 구간은 복사용이고, 일괄 피킹은 메뉴에서 지정한 마디 범위를 사용합니다.','Check Picking scope and the currently selected bar. Dragged ranges are used for copying; batch picking uses the bar range set in its menu.'),audience:'fretted'}
 ]}
];

export const editorHelpLabels={
 ko:{title:'악보 편집 도움말',subtitle:'입력부터 저장까지, 필요한 순서대로 찾아보세요.',search:'도움말 검색',placeholder:'예: Tie, 점음표, 복사, 저장',topics:'도움말 주제',empty:'일치하는 도움말이 없습니다.',clear:'검색 지우기',close:'도움말 닫기',tip:'기억하세요',example:'입력 순서',count:'개 주제'},
 en:{title:'Score editor help',subtitle:'Find the steps you need, from entry to saving.',search:'Search help',placeholder:'Try: tie, dotted, copy, save',topics:'Help topics',empty:'No matching help topics.',clear:'Clear search',close:'Close help',tip:'Remember',example:'Entry sequence',count:' topics'}
};
export function scoreEditorHelpContent(language,instrument){
 const locale=language==='en'?'en':'ko',audience=['piano','drums'].includes(instrument)?instrument:'fretted';
 const applicable=item=>!item.audience||item.audience===audience;
 const localize=value=>Array.isArray(value)?value.map(localize):value&&typeof value==='object'?(value.ko!==undefined?localize(value[locale]):Object.fromEntries(Object.entries(value).map(([key,v])=>[key,localize(v)]))):value;
 return topics.filter(applicable).map(topic=>localize({...topic,...(topic.id==='picking'&&audience!=='fretted'?{title:text('빔·반복','Beams and repeats')}:{}),blocks:topic.blocks.filter(applicable).map(block=>({...block,...(block.rows?{rows:block.rows.filter(applicable)}:{})}))}));
}
