import test from 'node:test';
import assert from 'node:assert/strict';
import {createBlankDocument,blankMeasure,compileDocumentV2} from '../src/etudes/scoreModel.js';
import {copyScoreRange,pasteScoreRange,scoreRangeClipboard} from '../src/etudes/scoreRangeClipboard.js';
import {copyGripToNext} from '../src/etudes/scoreLineCommands.js';
const fixture=()=>{const d=createBlankDocument();d.measures.push(blankMeasure());d.measures[0].events.forEach((e,i)=>{e.rest=false;e.blank=false;e.notes=[{id:'note-'+i,string:1,fret:i+1}];});return d;};
test('partial range pastes at cursor, preserves other positions and gives fresh identities',()=>{const d=fixture(),clip=copyScoreRange(d,{start:{bar:0,event:1},end:{bar:0,event:2}});const next=pasteScoreRange(d,{bar:1,event:1},clip);assert.deepEqual(next.measures[1].events.slice(1,3).map(e=>e.notes[0].fret),[2,3]);assert.equal(next.measures[1].events[0].blank,true);assert.equal(next.measures[1].events[3].blank,true);assert.notEqual(next.measures[1].events[1].id,d.measures[0].events[1].id);assert.deepEqual(compileDocumentV2(next).errors,[]);assert.equal(d.measures[1].events[1].blank,true);});
test('line-copy and source edits never mutate Ctrl+C snapshot; repeated pastes work',()=>{let d=fixture();scoreRangeClipboard.current=copyScoreRange(d,{start:{bar:0,event:0},end:{bar:0,event:1}});const snapshot=JSON.stringify(scoreRangeClipboard.current);d=copyGripToNext(d,{bar:0,event:2,string:1}).document;d.measures[0].events[0].notes[0].fret=9;assert.equal(JSON.stringify(scoreRangeClipboard.current),snapshot);let next=pasteScoreRange(d,{bar:1,event:0},scoreRangeClipboard.current);next=pasteScoreRange(next,{bar:1,event:2},scoreRangeClipboard.current);assert.deepEqual(next.measures[1].events.map(e=>e.notes[0].fret),[1,2,1,2]);assert.equal(JSON.stringify(scoreRangeClipboard.current),snapshot);});
test('reverse multi-bar range appends bars without modifying its source',()=>{const d=fixture(),clip=copyScoreRange(d,{start:{bar:1,event:1},end:{bar:0,event:2}}),next=pasteScoreRange(d,{bar:1,event:2},clip);assert.equal(next.measures.length,3);assert.deepEqual(compileDocumentV2(next).errors,[]);assert.equal(d.measures.length,2);});
