import test from 'node:test';import assert from 'node:assert/strict';
import {createBlankDocument,compileDocumentV2,ticksOf,tupletGroups,cloneMeasure} from '../src/etudes/scoreModel.js';
import {ensureTriplet,removeTriplet} from '../src/etudes/tuplets.js';
import {enterFret,deleteTone,setRest,nextEntry,setEventDuration} from '../src/etudes/editorCommands.js';
import {scoreTimeline} from '../src/etudes/scorePlayback.js';
import {rhythmGroups} from '../src/etudes/tabRhythm.js';
import {setBeamBefore} from '../src/etudes/beamOverrides.js';
const at=event=>({bar:0,event,string:6});
function triplets(){let d=createBlankDocument();for(let beat=0;beat<4;beat++){d=ensureTriplet(d,at(beat*3));for(let i=0;i<3;i++){d=enterFret(d,at(beat*3+i),9);d=enterFret(d,{...at(beat*3+i),string:5},7);}}return d;}
test('12 chord triplets fill exactly 1920 ticks; three occupy exactly one beat',()=>{const d=triplets(),events=d.measures[0].events;assert.equal(events.length,12);assert(events.every(e=>ticksOf(e)===160));assert.equal(events.reduce((s,e)=>s+ticksOf(e),0),1920);assert.deepEqual(tupletGroups(events),[[0,1,2],[3,4,5],[6,7,8],[9,10,11]]);assert.deepEqual(rhythmGroups(events),tupletGroups(events));const compiled=compileDocumentV2(d);assert.deepEqual(compiled.errors,[]);assert.deepEqual(compiled.issues,[]);for(const bpm of [60,80,137,240]){const timeline=scoreTimeline(compiled.score,bpm);assert.equal(timeline.events.length,24);timeline.events.forEach((e,i)=>{assert(Math.abs(e.start-Math.floor(i/2)/3*60/bpm)<1e-12);assert(Math.abs(e.duration-60/bpm/3)<1e-12);});assert.equal(timeline.duration,4*60/bpm);}assert.equal(nextEntry(d,at(11)).cursor.bar,1);});
test('view option, tuplets and beam edits persist with unchanged sound timing',()=>{const d=triplets();d.viewSettings={tabRhythm:false};const custom=setBeamBefore(d,at(1),'break'),loaded=JSON.parse(JSON.stringify(custom));assert.deepEqual(loaded,custom);assert.deepEqual(scoreTimeline(compileDocumentV2(d).score),scoreTimeline(compileDocumentV2(loaded).score));const copy=cloneMeasure(d.measures[0]);assert.notEqual(copy.events[0].tuplet.groupId,d.measures[0].events[0].tuplet.groupId);assert.equal(copy.events[0].tuplet.groupId,copy.events[2].tuplet.groupId);});
test('partial deletion and explicit rests retain exact tuplet timing',()=>{const d=triplets(),one=deleteTone(d,at(1)),empty=deleteTone(one,{...at(1),string:5});assert.equal(one.measures[0].events[1].notes.length,1);assert.equal(empty.measures[0].events[1].blank,true);assert.equal(ticksOf(empty.measures[0].events[1]),160);const rest=setRest(empty,at(1));assert.equal(rest.measures[0].events[1].blank,false);for(const doc of [one,empty,rest]){assert.deepEqual(compileDocumentV2(doc).errors,[]);if(doc===empty)assert(compileDocumentV2(doc).issues.some(issue=>issue.includes('그룹 미완성')));else assert.deepEqual(compileDocumentV2(doc).issues,[]);}assert.throws(()=>setEventDuration(d,at(1),'4'));});
test('safe conversion, removal and deletion never overwrite following music',()=>{const full=triplets();assert.throws(()=>removeTriplet(full,at(1)));const cleared=removeTriplet(full,at(1),{clear:true});assert.deepEqual(compileDocumentV2(cleared).issues,[]);assert.deepEqual(cleared.measures[0].events.slice(1),full.measures[0].events.slice(3));let d=ensureTriplet(createBlankDocument(),at(0));d=enterFret(d,at(2),7);const normal=removeTriplet(d,at(1));assert.equal(normal.measures[0].events[2].notes[0].fret,7);assert.equal(normal.measures[0].events[2].onset,480);assert.deepEqual(compileDocumentV2(normal).issues,[]);assert.throws(()=>ensureTriplet(full,at(0),'16'));});
