import {createPortal} from 'react-dom';
import {useEffect,useRef,useState,memo} from 'react';
import {GROOVE_TONES} from './groove.js';
import {METRONOME_TONE_OPTIONS} from './options.js';
import {previewMetronomeTone,stopMetronomePreview} from '../audio/metronomePreview.js';
export default memo(function GrooveTonePicker({row,r,changeRow}){
 const [open,setOpen]=useState(false),[position,setPosition]=useState({}),[error,setError]=useState(''),menu=useRef(null),root=useRef(null),trigger=useRef(null);
 const close=()=>{setOpen(false);stopMetronomePreview();};
 useEffect(()=>{if(!open)return;const place=()=>{const rect=trigger.current.getBoundingClientRect(),width=Math.min(320,window.innerWidth-24),height=Math.min(250,window.innerHeight-32);const theme=getComputedStyle(root.current);setPosition({...Object.fromEntries(['--groove-surface','--groove-text','--groove-border','--groove-control'].map(k=>[k,theme.getPropertyValue(k)])),left:Math.max(12,Math.min(rect.left,window.innerWidth-width-12)),top:Math.max(12,Math.min(rect.bottom+5,window.innerHeight-height-12)),width,maxHeight:height});};place();const outside=e=>{if(!root.current?.contains(e.target)&&!menu.current?.contains(e.target))close();},escape=e=>{if(e.key==='Escape'){e.stopPropagation();close();trigger.current?.focus();}},other=e=>{if(e.detail!==root.current)close();};window.addEventListener('pointerdown',outside);window.addEventListener('keydown',escape);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);window.addEventListener('riffDropdownOpen',other);return()=>{window.removeEventListener('pointerdown',outside);window.removeEventListener('keydown',escape);window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);window.removeEventListener('riffDropdownOpen',other);stopMetronomePreview();};},[open]);
 return <div className="grooveTrackName" ref={root}><button ref={trigger} type="button" className="grooveToneTrigger" aria-label={`${r+1}행 음색`} aria-expanded={open} aria-haspopup="dialog" onClick={()=>{if(open)close();else{window.dispatchEvent(new CustomEvent('riffDropdownOpen',{detail:root.current}));setError('');setOpen(true);}}}>{GROOVE_TONES.find(([id])=>id===row.tone)?.[1]}{row.muted?' · 끔':''}<span aria-hidden="true">⌄</span></button>{open&&createPortal(<div ref={menu} className="grooveTonePopup" style={position} role="dialog" aria-label={`${r+1}행 음색 선택`}><div className="grooveToneChoices">{GROOVE_TONES.map(([id,label])=><div className="grooveToneChoice" key={id}><button type="button" aria-pressed={row.tone===id} onClick={()=>{changeRow(r,{tone:id});close();trigger.current?.focus();}}>{label}</button><button type="button" aria-label={label+' 미리듣기'} onClick={()=>{setError('');void previewMetronomeTone(METRONOME_TONE_OPTIONS.find(t=>t.id===id)).catch(()=>setError('음원을 불러오지 못했습니다. 다시 눌러주세요.'));}}>▶</button></div>)}</div><button type="button" className="grooveToneMute" onClick={()=>{changeRow(r,{muted:!row.muted});close();}}>{row.muted?'음소거 해제':'이 행 음소거'}</button>{error&&<span role="status">{error}</span>}</div>,document.body)}</div>;
});
