const CELESTIAL_ECLIPSE_ROOT = "/assets/maps/celestial-eclipse-clocktower";
const CELESTIAL_ECLIPSE_PREVIEW = "/assets/maps/previews/celestial-eclipse-clocktower-current.jpg";

export const CELESTIAL_ECLIPSE_CLOCKTOWER_MAP_SKIN = Object.freeze({
  id: "celestial-eclipse-clocktower",
  kind: "layered",
  label: "천공의 월식 시계탑",
  nameKo: "천공의 월식 시계탑",
  nameEn: "Celestial Eclipse Clocktower",
  description: "월식과 천문환이 회전하는 천공의 시계탑",
  mobileOnly: false,
  portraitOnly: true,
  previewImage: CELESTIAL_ECLIPSE_PREVIEW,
  pickerPreviewImage: CELESTIAL_ECLIPSE_PREVIEW,
  performance: Object.freeze({
    mobileGameplay: Object.freeze({
      mode: "full",
      audit: Object.freeze({
        completed: true,
        contentFingerprint: "e0d955fa",
        activeCssAnimations: 0,
        ambientEventLayers: 0,
        filteredElements: 0,
        particleElements: 0,
        sharedSpriteSubscribers: 1,
      }),
    }),
  }),
  referenceViewport: Object.freeze({
    width: 768,
    height: 1664,
    deviceWidth: 390,
    deviceHeight: 844,
  }),
  background: Object.freeze({
    id: "celestial-eclipse-clocktower-background",
    src: `${CELESTIAL_ECLIPSE_ROOT}/background/celestial_eclipse_clocktower_bg_768x1664.webp`,
    fallbackSrc: `${CELESTIAL_ECLIPSE_ROOT}/background/celestial_eclipse_clocktower_bg_768x1664.png`,
    fit: "cover",
    position: "50% 50%",
    locked: true,
  }),
  animatedBackdrop: Object.freeze({
    id: "celestial-eclipse-astrolabe",
    src: `${CELESTIAL_ECLIPSE_ROOT}/astrolabe/eclipse_astrolabe_48f_8x6.webp`,
    fallbackSrc: `${CELESTIAL_ECLIPSE_ROOT}/astrolabe/eclipse_astrolabe_48f_8x6.png`,
    frameCount: 48,
    framesPerSecond: 12,
    columns: 8,
    rows: 6,
    cellWidth: 320,
    cellHeight: 320,
    anchorX: 0.5,
    anchorY: 0.5,
    centerX: 0.5,
    top: 0.005,
    width: 0.65,
  }),
  foregroundOccluder: Object.freeze({
    id: "celestial-eclipse-clocktower-foreground",
    src: `${CELESTIAL_ECLIPSE_ROOT}/foreground/clocktower_foreground_occluder_768x1664.webp`,
    fallbackSrc: `${CELESTIAL_ECLIPSE_ROOT}/foreground/clocktower_foreground_occluder_768x1664.png`,
    fit: "cover",
    position: "50% 50%",
  }),
  assetCatalog: Object.freeze([]),
  ambientEvents: Object.freeze([]),
  layout: Object.freeze([]),
  layers: Object.freeze([]),
});
