const GACHA_ARCADE_ROOT = "/assets/maps/gacha-arcade";
const GACHA_ARCADE_RUNTIME_BACKGROUND = `${GACHA_ARCADE_ROOT}/runtime/FRETIVA_GACHA_ARCADE_MAP_BASE_RUNTIME.png`;
const GACHA_ARCADE_CANVAS = Object.freeze({ width: 1536, height: 3328 });
const GACHA_ARCADE_RENDER_ORDER = Object.freeze([
  "integrated_background",
  "three_claw_window_layers",
  "star_light_ring",
  "gameplay",
  "guitar",
  "HUD",
]);

const sprites = Object.freeze([
  {
    id: "claw_left_mid",
    src: `${GACHA_ARCADE_ROOT}/spritesheets/claw_left_mid_sheet_6x4.png`,
    columns: 6,
    rows: 4,
    frameCount: 24,
    framesPerSecond: 4,
    durationMs: 6000,
    delayMs: 0,
    direction: "left-wall to right",
    scaleChange: false,
    placement: Object.freeze({ x: 88, y: 1125, width: 300, height: 280 }),
    clipRect: Object.freeze({ x: 0, y: 0, width: 300, height: 280 }),
  },
  {
    id: "claw_right_upper",
    src: `${GACHA_ARCADE_ROOT}/spritesheets/claw_right_upper_sheet_6x4.png`,
    columns: 6,
    rows: 4,
    frameCount: 24,
    framesPerSecond: 4,
    durationMs: 6000,
    delayMs: 1800,
    direction: "right-wall to left",
    scaleChange: false,
    placement: Object.freeze({ x: 1180, y: 690, width: 290, height: 250 }),
    clipRect: Object.freeze({ x: 0, y: 0, width: 290, height: 250 }),
  },
  {
    id: "claw_right_lower",
    src: `${GACHA_ARCADE_ROOT}/spritesheets/claw_right_lower_sheet_6x4.png`,
    columns: 6,
    rows: 4,
    frameCount: 24,
    framesPerSecond: 4,
    durationMs: 6000,
    delayMs: 3600,
    direction: "right-wall to left",
    scaleChange: false,
    placement: Object.freeze({ x: 1165, y: 2160, width: 320, height: 310 }),
    clipRect: Object.freeze({ x: 0, y: 0, width: 320, height: 310 }),
  },
  {
    id: "star_light_ring",
    src: `${GACHA_ARCADE_ROOT}/spritesheets/star_light_ring_sheet_6x4.png`,
    columns: 6,
    rows: 4,
    frameCount: 24,
    framesPerSecond: 6,
    durationMs: 4000,
    delayMs: 0,
    scaleChange: false,
    placement: Object.freeze({ x: 388, y: 260, width: 760, height: 601 }),
  },
].map((sprite) => Object.freeze(sprite)));

export const GACHA_ARCADE_MAP_SKIN = Object.freeze({
  id: "gacha-arcade",
  kind: "layered",
  label: "인형뽑기방",
  nameKo: "인형뽑기방",
  nameEn: "Gacha Arcade",
  description: "고정된 세 대의 뽑기 기계 안에서 집게와 별 조명만 움직이는 아케이드",
  mobileOnly: false,
  portraitOnly: true,
  previewImage: GACHA_ARCADE_RUNTIME_BACKGROUND,
  pickerPreviewImage: GACHA_ARCADE_RUNTIME_BACKGROUND,
  performance: Object.freeze({
    mobileGameplay: Object.freeze({
      mode: "full",
      audit: Object.freeze({
        completed: true,
        contentFingerprint: "194a638f",
        activeCssAnimations: 0,
        ambientEventLayers: 0,
        filteredElements: 0,
        particleElements: 0,
        sharedSpriteSubscribers: 1,
      }),
    }),
  }),
  referenceViewport: Object.freeze({
    ...GACHA_ARCADE_CANVAS,
    deviceWidth: 390,
    deviceHeight: 844,
  }),
  background: Object.freeze({
    id: "gacha-arcade-background-v2",
    src: GACHA_ARCADE_RUNTIME_BACKGROUND,
    masterSrc: `${GACHA_ARCADE_ROOT}/FRETIVA_GACHA_ARCADE_MAP_BASE_INTEGRATED.png`,
    fit: "fill",
    position: "50% 50%",
    locked: true,
  }),
  runtimeAnimation: Object.freeze({
    version: "2.0.0",
    canvasWidth: GACHA_ARCADE_CANVAS.width,
    canvasHeight: GACHA_ARCADE_CANVAS.height,
    clockFramesPerSecond: 10,
    renderOrder: GACHA_ARCADE_RENDER_ORDER,
    sprites,
    preloadSources: Object.freeze(sprites.map((sprite) => sprite.src)),
  }),
  assetCatalog: Object.freeze([]),
  ambientEvents: Object.freeze([]),
  layout: Object.freeze([]),
  layers: Object.freeze([]),
});
